### ISSUE TITLE
Audio doesn't play on mobile devices (Working on)

### ISSUE THREAD

**Issue by Legoman99573** [Mindgamesnl/OpenAudioMc#10]
I was adding this as it doesn't seem to play the files, but I get the media volume option when I try to change the volume. I was hoping if you can fix this please as I can't find a fix for it =/

**Comment by Legoman99573** [comment]
Get firefox ;)

**Comment by Mindgamesnl** [comment]
Lock mobile browsers.

working on it

**Comment by Legoman99573** [comment]
We can get it to work on the Firefox app, so there is a workaround to that ;)

**Comment by Mindgamesnl** [comment]
Right, but don't close the issue when the solution is not inplemented yet

**Comment by Legoman99573** [comment]
true, i did get the mobile part ready, just got to implement the QR Code in the settings ;)

**Comment by Mindgamesnl** [comment]
Browser detection is easy, workin on it... ;)
