### ISSUE TITLE
Feature Request - Ambience Sound

### ISSUE THREAD

**Issue by GrammaticaDW** [Mindgamesnl/OpenAudioMc#100]
actually a link in the config that can be played if the player is not in a region with sound or in a speaker radius.

Like in the way it is now with the regions. Not that the music would start playing from the beginning. I think you know what I mean, otherwise I will send more clarification :)

thank you.

**Comment by Mindgamesnl** [comment]
I'll start work on bringing this feature back tomorrow

**Comment by Mindgamesnl** [comment]
Almost a year later, work in progess
