### ISSUE TITLE
OpenAudioMC Hue (room configuration) not working

### ISSUE THREAD

**Issue by michieldesmet** [Mindgamesnl/OpenAudioMc#101]
**OpenAudioMc Version:5.2** 

**Spigot Version:1.13.2-R0.1-SNAPSHOT**

**Description of the problem:Room configuration bug** 
NL: Als ik mijn openaudio client opstart en ik verbind mijn Hue bridge via de http en ik selecteer mijn kamer dan zou dat normaal denk ik moeten werken. 
Maar als ik het hue command "/oa hue set michybox [1,2] 255 0 255 255" gebruik veranderd hij de lampen niet van de geselecteerde kamer maar van een andere kamer.

EN: If I start my open audio client and I connect my Hue bridge via the http and I select my room then I think that should work normally.
But if I use the hue command "/oa hue set michybox [1,2] 255 0 255 255" he does not change the lamps of the selected room but of another room.

**Comment by Mindgamesnl** [comment]
on it

**Comment by Mindgamesnl** [comment]
resolved
