### ISSUE TITLE
The command to create speakers from the console is broken in 1.14.4

### ISSUE THREAD

**Issue by aescraftbr** [Mindgamesnl/OpenAudioMc#108]
**Describe the bug**
The command /oa speaker from the console is broken.

**To Reproduce**

1. /oa speaker set world 1000015 105 999997 https://www.dropbox.com/s/wju3truihv25q2y/Stranglehold.mp3?dl=0

**Expected behavior**
The speaker should work the same way as the one from the /speaker command, but this from console trows a console error.

**Screenshots**
Little gif showing the error:
https://cdn.discordapp.com/attachments/245498457681428480/621617601969127424/new.gif

**Additional context**
Using paper 1.14.4 192
OA 6.0.3.4

Console:

```
12.09 03:55:48 [Server] WARN java.lang.UnsupportedOperationException: Must change block type
12.09 03:55:48 [Server] WARN at org.bukkit.craftbukkit.v1_14_R1.block.CraftSkull.setSkullType(CraftSkull.java:170)
12.09 03:55:48 [Server] WARN at com.craftmend.openaudiomc.spigot.modules.commands.subcommands.SpeakersSubCommand.onExecute(SpeakersSubCommand.java:112)
12.09 03:55:48 [Server] WARN at com.craftmend.openaudiomc.spigot.modules.commands.command.SpigotMainCommand.onCommand(SpigotMainCommand.java:52)
12.09 03:55:48 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
12.09 03:55:48 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
12.09 03:55:48 [Server] WARN at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739)
12.09 03:55:48 [Server] WARN at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:701)
12.09 03:55:48 [Server] WARN at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:456)
12.09 03:55:48 [Server] WARN at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418)
12.09 03:55:48 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075)
12.09 03:55:48 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919)
12.09 03:55:48 [Server] WARN at java.lang.Thread.run(Thread.java:748)
```

**Fix ideas:**
ApocalypsjeNL said this in discord:

> ah I see what is wrong, @Mats // Mindgamesnl you're using an legacy api call while you specified the 1.13 version in the plugin.yml because when using api version 1.13 (or higher) you need to set the block to PLAYER_SKULL instead of SKULL to set the skull owner

**Comment by Mindgamesnl** [comment]
Issue has been identified: reflecting error on my end

**Comment by Mindgamesnl** [comment]
Should be fixed for next build/release

**Comment by aescraftbr** [comment]
Bump, as it's not working in 6.0.4
