### ISSUE TITLE
Media Volume

### ISSUE THREAD

**Issue by aescraftbr** [Mindgamesnl/OpenAudioMc#110]
It's a simple feature, like we can set the ID, loop, pickup and other media options, we should be able to set the media master volume.

For example:

/oa play @a URL {volume:50}

Will play the audio at 50% of the user selected volume.

If in the browser, the volume is 100%, the volume of this media will be 50% of the volume of the player. 

If the volume in the browser is 50%, this media volume would be 50% of that, so it would be 25%.

**When this is important**
If a player has a Radio system, and speakers set in the world, the speakers would compete with the radio system.

With the capability of setting the volume of the media of the radio to 50%, for example, when near a speaker, the sound from the speaker would be higher than the one from the radio, thus, creating some sort of "priority".

Thanks!

**Comment by aescraftbr** [comment]
Alternatively (also, I think it's even better), when near the speaker, the audio that is sent from sources other than the speaker (region or simple command) could fade out while the audio fom speakers fade in.

This could be optional.

Example:

/oa play @A URL {speakerfadeout:true}

**Comment by Mindgamesnl** [comment]
Volume argument is worth looking into, as for your second proposal, that would be a no because its to specific and not applicable to other use cases than your project.

**Comment by ImranDoet** [comment]
@Mindgamesnl implemented yet? I want to contribute and might help by adding the enhancement tickets.

**Comment by Mindgamesnl** [comment]
Nope, it hasn't yet.

Feel free to pick it up if you want to, otherwise, I'll do it soon

**Comment by Mindgamesnl** [comment]
Implemented in the webclient, working on plugin update for it and is something that will come soon
