### ISSUE TITLE
Disconnect event is not accessible/working

### ISSUE THREAD

**Issue by aescraftbr** [Mindgamesnl/OpenAudioMc#111]
**Describe the bug**
I'm using skript-mirror (reflection addon) to get the event from OA mc.
The connect event works flawless. But the disconnect one isn't working.

**To Reproduce**

This is the skript mirror code:

```
import:
  com.craftmend.openaudiomc.spigot.modules.players.events.ClientDisconnectEvent
  com.craftmend.openaudiomc.spigot.modules.players.events.ClientConnectEvent

on ClientDisconnectEvent:
  broadcast "Someone disconnected."
  set {_p} to event.getPlayer()
  broadcast "Who disconnected is: {_p} = %{_p}%"

on ClientConnectEvent:
  broadcast "Someone connected."
  set {_p} to event.getPlayer()
  broadcast "Who connected is: {_p} = %{_p}%"
```

The "on ClientConnectEvent" is working.
The "on ClientDisconnectEvent" isn't working. 

**Expected behavior**
Both should work.

**Screenshots**
This shows that the broadcast works when the player connects (little proof that On Client Connect Event woks):
https://i.imgur.com/yASPOpQ.png

**Desktop (please complete the following information):**
paper 196
NO bungeecord
OA 6.0.3.4
offline mode

**Comment by Mindgamesnl** [comment]
Fixed for the newest build
