### ISSUE TITLE
When i restart the server, the speakers 'forget' their range setting

### ISSUE THREAD

**Issue by Aaron2550** [Mindgamesnl/OpenAudioMc#112]
**Describe the bug**
When i restart the server the speakers 'forget' their range setting

**To Reproduce**
1. Get a speaker with a custom range setting, lets say 60, and place it.
2. Restart the server
3. Get a new /audio link and boom, default range. 

**Expected behavior**
The range setting is saved.

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise Version 1903 Build 18362.418
 - Browser: Chrome (Vivaldi)
 - Version: 2.8.1664.44 (Stable channel) (32-Bit)
 - User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.121 Safari/537.36 Vivaldi/2.8.1664.44
- Paper Version: This server is running Paper version git-Paper-221 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
**Additional context**
none

**Comment by Mindgamesnl** [comment]
Fixed for next release, thank you for reporting :)
