### ISSUE TITLE
Speaker changes (visually)

### ISSUE THREAD

**Issue by Andre601** [Mindgamesnl/OpenAudioMc#118]
**Is your feature request related to a problem? Please describe.**
One part of the feature request is related to the lore of the speaker item inside the inventory, where it is too long for GUI settings like "auto"

**Describe the solution you'd like**
I would like to have the inventory title display the currently set range for the speaker since if the range is bigger than 16 or smaller than 2, none of the noteblocks have the enchanted glow and therefore you aren't able to tell what the current range is set to.

Another issue is, that the lore of the speaker item is way off the screen when using a GUI setting like auto. (See image)
Solutions could be to either have the link in a separate line or having the link only display the source URL instead of `https://api.openaudiomc.net/stream.php?u=<link>`

![2019-11-27_14 39 40](https://user-images.githubusercontent.com/11576465/69727951-c97a8980-1123-11ea-8029-1c18078d72b9.png)

**Describe alternatives you've considered**
There aren't really any alternatives other than switching GUI size temporary, which isn't really a good solution.

**Additional context**
Running PaperMC 1.14.4 (build 230) and OpenAudioMC 6.0.4

**Comment by Andre601** [comment]
Will this ever be considered?

**Comment by Mindgamesnl** [comment]
Probably not since this is done as middleware to translate between sources while registering it and there isn't any easy way to reverse it (same goes for the youtube addon, etc etc)

**Comment by Andre601** [comment]
I can't really see where this wouldn't be possible to change.
Like at least have the currently set distance of the speaker in the GUI title seems like something doable as (like you can see in the screenshots) distances larger than 16 aren't displayed.

Alternatively, could a re-ordering, where you put the speaker on the middle slot (on a separate row?) be an idea to make the text more readable.
And seriously... Adding a separate line to the lore of the Item shouldn't be *that* difficult.

**Comment by Mindgamesnl** [comment]
What I referred to as displaying the original URL instead of the changed one which would not be worth the effort, I'll play around with re-ordering the GUI itself (already had some things in mind to select a set of speakers instead of only individual ones, so has to be done either way)

**Comment by Andre601** [comment]
> I'll play around with re-ordering the GUI itself (already had some things in mind to select a set of speakers instead of only individual ones, so has to be done either way)

Maybe as an additional setting in OpenAudioMc Plus?
I could see a lot of benefits of having a way to alter the range of the speakers there and maybe even some other settings... But this would then require the plugin to be reloaded or the server to be restarted.
Perhaps a system like LuckPerms' web editor - where data is temporary saved and applied using commands - could also be a possible idea?

**Comment by Mindgamesnl** [comment]
Don't think that something like this should be done in plus (or any web editor), it doesn't make sense to require more steps from the user when the same can be achieved with fewer interactions/steps in the same window they already have an open and clear understanding of what's going on (Minecraft)

Shows and Presets (region-based client themes and preferences) do have an appeal to be integrated into plus because that's considerably more convenient than half a dozen config files, but speakers have the appeal of shift-clicking a few and not having to look up coordinates or any other id's
