### ISSUE TITLE
Mac Problem

### ISSUE THREAD

**Issue by phlphilipp** [Mindgamesnl/OpenAudioMc#119]
**OpenAudioMc Version:** 
6.0.3.5

**Spigot Version:**
git-Spigot-5695bca-53fccdf MC:1.12.2 1.12.2-R0.1-SNAPSHOT

**Description of the problem:** 
One of our users always gets this bug, but his link works 100% on my computer.

![WhatsApp Image 2020-01-02 at 15 13 16](https://user-images.githubusercontent.com/59444496/71671543-8ee3bc80-2d73-11ea-9530-737a74bcf30a.jpeg)

**Comment by SnowBlinderP** [comment]
@phlphilipp Is he Using AntiVirus / Anti-Malware Software?

**Comment by phlphilipp** [comment]
No, its a fresh Mac Book. Only the standart apple stuff.

**Comment by SnowBlinderP** [comment]
@phlphilipp What Type of Connection? (Mobile - Landline - Cable - Dialup)
Does the Problem only appear on this Connection or everywhere?

**Comment by phlphilipp** [comment]
@SnowBlinderP Vodafone GigaCube
it works for me with no problems, also for others.
atm he is the only one with that error

**Comment by SnowBlinderP** [comment]
@phlphilipp Do other Devices work using the GigaCube?
Does he have a Landline (DSL or something) to test?
I know from Personal Experience that Vodafone sometimes is a bit "picky" on RT Connections

**Comment by phlphilipp** [comment]
Normal internet works fine, also on the Mac.
Probably Vodafone then...
Thanks

**Comment by SnowBlinderP** [comment]
@phlphilipp Sorry to hear that.
That's what i thought - 
The Information that was given to me from a VF Partner is that The GigaCube is more aimed at "Multimedia" like Youtube Spotify and Stuff - Not RT Connections and "cool Internet Systems"

**Comment by phlphilipp** [comment]
Still many thanks!
