### ISSUE TITLE
Add residence support

### ISSUE THREAD

**Issue by tianji1993** [Mindgamesnl/OpenAudioMc#123]
**Is your feature request related to a problem? Please describe.**
Well now the plugin only support worldguard, although it's good enough, there still have so many server using Residence plugin: https://www.spigotmc.org/resources/residence-1-7-10-up-to-1-15.11480/
**Describe the solution you'd like**
Can you please add the support for it?

**Describe alternatives you've considered**

**Additional context**
https://www.spigotmc.org/resources/residence-1-7-10-up-to-1-15.11480/
https://zrips.net/Residence/
https://www.zrips.net/residence/api/

**Comment by Mindgamesnl** [comment]
Not planned and don't have the time to do so, but feel free to open a pull request.

**Comment by Mindgamesnl** [comment]
No response.
