### ISSUE TITLE
sound no longer goes out

### ISSUE THREAD

**Issue by Blueeyestar** [Mindgamesnl/OpenAudioMc#125]
Openaudiomc-Version: 6.1.4

Paperversion: Paper version git-Paper-146 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

good day the Openaudiomc has had a problem since the Update. In the past, the sound stopped when you were 16 blocks away from the speaker. now the sound continues regardless of how far you go.

Although I entered 16 as the range:

609c980c-e696-4c32-8aa0-ee97fee6d6a7:
world: world
x: 89
y: 74
z: 322
radius: 16

**Comment by Mindgamesnl** [comment]
Fixed

**Comment by Blueeyestar** [comment]
when will the fixed version come out?

**Comment by Mindgamesnl** [comment]
It already did in the form of a web client update, you might need to force reload (google how to do that for your browser), if you don't want to do that, it'll update automatically for you

**Comment by Blueeyestar** [comment]
oh so thought was due to my .jar file. OK then I understood it too. Thank you for the info. stay healthy and happy easter

**Comment by Mindgamesnl** [comment]
You too buddy, enjoy and make the best of it :)
