### ISSUE TITLE
Music play weird.

### ISSUE THREAD

**Issue by GamenMetMark** [Mindgamesnl/OpenAudioMc#127]
**Describe the bug**
I have download the plugin today and set it in my server but when i play i video it will not start at the beginning of a song.

**To Reproduce**
1. Type the command: /oa play @a https://www.youtube.com/watch?v=x5yR1iN9kBU
2. Then it is not starting from the begin

**Expected behavior**
I really just hope that this is fixable.

**Screenshots**
- None

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox (but chrome is not working aswell)
 - Version: 75.0

**Additional context**
I really hope that it will be fixed.

**Comment by SnowBlinderP** [comment]
Issue does not seem to be directly related to Youtube Usage

Discussion: [SnowDNS/OpenAudioMC-YT#4](https://git.snowdns.de/SnowBlinderP/openaudioyt-addon/issues/4)

**Comment by Mindgamesnl** [comment]
Issue resolved in https://github.com/Mindgamesnl/OpenAudioMc/commit/ff66f87ae9f070a73f22315f515b79cc5afd07bf

Forcefully reloading the client installs it right away, or wait a few minutes before reopening your web client after having closed it.

You don't need to update the plugin
