### ISSUE TITLE
Allow /openaudio plus to be executed by console

### ISSUE THREAD

**Issue by Andre601** [Mindgamesnl/OpenAudioMc#128]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Make `/openaudio plus` executable by the console, to access the webpanel.  
This would allow a more secure handling of the command without the risk of granting the permission, while having the risk of possible hijacks of your account (unlikely but still possible)

**Describe alternatives you've considered**
Only alternative would be to run the command in-game.

**Additional context**
While having the command behind a permission is a somewhat okay approach is it still risky because it is still possible that a malicious user could access the webpanel by f.e. tricking the owner into giving them the permission, or OP.

Having the command being executable through console would make it possible to change settings without such a possible risk, since you don't have to give such permissions in the first place.

**Comment by Mindgamesnl** [comment]
On it, will be adding it today as well as an option to restrict it to console only (so no command blocks or players with OP), you have a valid point

**Comment by Mindgamesnl** [comment]
Implemented in https://github.com/Mindgamesnl/OpenAudioMc/commit/d0483ce7cedac5a19bc3b89366ac893205bd5680, pending for next release.
