### ISSUE TITLE
Config.yml gets constantly reset

### ISSUE THREAD

**Issue by Andre601** [Mindgamesnl/OpenAudioMc#130]
**Describe the bug**
When changing values in the config, does OpenAudioMc constantly reset it back to the default values, causing issues.

**To Reproduce**
1. Install OpenAudioMc on a server
2. Let it create a fresh config.yml
3. Change settings in the config.yml
    - Settings I changed:
`options.send-on-join` set to `false`
`options.remind-to-connect` set to `false`
4. Save changes
5. Restart server

**Expected behavior**
OpenAudioMc should use the new values and not reset the config.

**Screenshots**
Console displays the following text from OpenAudioMc, indicating that it migrates stuff???
![image](https://user-images.githubusercontent.com/11576465/80216427-51ff4680-863e-11ea-899f-7d594dde702c.png)

Text version: https://paste.helpch.at/fofuwerepi.sql

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Google Chrome
 - Versions
    - OpenAudioMc: 6.2

**Additional context**

**Comment by Mindgamesnl** [comment]
Do you get any notes about migration or does it just _happen_
Also, when did you download the jar? I pushed a fix yesterday night (cuz of timezones, that's about 20 hours ago) fixing some migration issues as a patch instead of update.

**Comment by Mindgamesnl** [comment]
Edit: I now see your screenshot, didn't seem to load or you edited it

**Comment by Andre601** [comment]
I edited it, because GitHub did a derp.
And by patch you mean you altered the latest release on Spigot?

**Comment by Mindgamesnl** [comment]
Yeah, I altered the release.
It points to a file on my webserver to download it (because of size limits on spigot) and replaced that one.

The same effect as an update but without bothering everyone for an update they might not need.

**Comment by Andre601** [comment]
I updated the plugin and the config has been migrated again.
Result being that the same values got changed to true again, despite the fact that the migration in the console mentions that the values are set to false...

**Comment by Andre601** [comment]
Yup. Changing the values again and restarting the server causes the config to reset yet again, so this bug is still existing.

**Comment by Mindgamesnl** [comment]
My gut tells me that the plugin not catching the changs and happily going right over them upon saving which it shouldn't do, to begin with, or the migration triggering when it's not supposed to since it should still just pick up the old values. Either way, it's a fuckup on my end.

I have a call scheduled with coworkers in a few minutes, will get on this right after.

**Comment by Mindgamesnl** [comment]
Should be fixed: https://github.com/Mindgamesnl/OpenAudioMc/compare/ebe1e5be59cd...b9eb3e59f97b

Testing asap and will roll it out afterward

**Comment by Andre601** [comment]
So, is that available as dev build or so?

**Comment by Mindgamesnl** [comment]
Not unless you compile it yourself, as said, ill get back to it, I'm currently at the office just working.

**Comment by Andre601** [comment]
Alright thanks.
Let me know when it is ready 😉

**Comment by Mindgamesnl** [comment]
Seems to be fixed, can you confirm?

**Comment by Andre601** [comment]
I can't because I'm not really a guy that wants to build jars from the source. Mainly because I could do something wrong, causing issues that shouldn't be there.

**Comment by Mindgamesnl** [comment]
https://download.openaudiomc.net/OpenAudioMc-6.2.jar

You can try that one if it works, I'll drop it as a patch later today with the development branch since that includes some fixes as well.

**Comment by Mindgamesnl** [comment]
Fixed, tested and released as the .2 patch on spigot.
