### ISSUE TITLE
Traincarts Stop

### ISSUE THREAD

**Issue by CodeDoctorDE** [Mindgamesnl/OpenAudioMc#131]
**Is your feature request related to a problem? Please describe.**
I start my sound in a area of my coaster but it doesn't stop.

**Describe the solution you'd like**
A stop sign

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by Mindgamesnl** [comment]
What exactly was on your sign?

**Comment by CodeDoctorDE** [comment]
There is a traincarts start sign, we need a stop sign

**Comment by Mindgamesnl** [comment]
I know dude, I asked what EXACTLY you put on the sign.

**Comment by Mindgamesnl** [comment]
And did you start it via a sign too?

**Comment by CodeDoctorDE** [comment]
Yes

**Comment by Mindgamesnl** [comment]
![image](https://user-images.githubusercontent.com/10709682/80588971-9c573d80-8a19-11ea-807c-34ac6470fb96.png)
SO this was your sign?...

**Comment by CodeDoctorDE** [comment]
xd no, which sign? the start sign?

**Comment by Mindgamesnl** [comment]
The start and the stop signs..

**Comment by CodeDoctorDE** [comment]
Is there already a start sign?

**Comment by CodeDoctorDE** [comment]
* stop

**Comment by Mindgamesnl** [comment]
![image](https://user-images.githubusercontent.com/10709682/80589058-c446a100-8a19-11ea-8af5-0e5211ba6bf8.png)

**Comment by Mindgamesnl** [comment]
Just send whatever the fuck was on all of your signs

so like 
```
[train]
boop
biep
```

Dude it aint that difficult, if you won't send them then I'm gonna close the issue.

**Comment by CodeDoctorDE** [comment]
[train]
play
a:desert

**Comment by Mindgamesnl** [comment]
Yes, that's one

**Comment by Mindgamesnl** [comment]
And the stop sign? what sound doesnt stop? If you wont profide details im closing this issue.

**Comment by CodeDoctorDE** [comment]
i want that the sound stops when i drive over this rail. How can i do this?

**Comment by Mindgamesnl** [comment]
try

[train]
play
stop

**Comment by CodeDoctorDE** [comment]
Ok thanks

**Comment by CodeDoctorDE** [comment]
And when i only want to stop this sound?

**Comment by Mindgamesnl** [comment]
A train can only have one sound.

**Comment by CodeDoctorDE** [comment]
Ok thanks :)
