### ISSUE TITLE
OpenAudioMc spams "Saving OpenAudioMc data with world save..." in console when no player is around

### ISSUE THREAD

**Issue by Andre601** [Mindgamesnl/OpenAudioMc#135]
**Describe the bug**
When no player is around (Can't confirm nor deny that this won't happen with players online) does OpenAudioMc spam the console with "Saving OpenAudioMc data with world save..." but to my knowledge is there no world-save option active

Log: https://paste.helpch.at/yelorazafe.md

**To Reproduce**
1. Join server
2. Leave server?

**Expected behavior**
The message shouldn't appear, or at least be a bit reduced.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome
 - Version OpenAudioMc 6.3

**Additional context**
My server doesn't have that many players online and this message just bloats the log files which is wasted storage space.

**Comment by Andre601** [comment]
In addition did OpenAudioMc also remove speakers for no reason other than them being "dead"

**Comment by Mindgamesnl** [comment]
We do this on the world save event, you might want to look into whats causing the save to be triggered for all your world when you have this option disabled in bukkit.

I can make it optional, but this hints at a deeper problem in your server (since you said it shouldn't fire in the first place)

**Comment by Mindgamesnl** [comment]
Removed logging for next release
