### ISSUE TITLE
OpenAudioMc deletes speakers for reason of being "dead"

### ISSUE THREAD

**Issue by Andre601** [Mindgamesnl/OpenAudioMc#136]
**Describe the bug**
I already mentioned this in #135 but decided to open a separate issue for it.
OpenAudioMc deletes saved speakers for the reason of them being "dead", even if you just set them before a server restart.

**To Reproduce**
1. Add any amount of speaker you want
    - I set speakers with range 20 and the link https://soundcloud.com/argofox/gj-disconscient
2. Stop the server
3. Start the server
4. OpenAudioMc should now mention something like `[OpenAudioMc] Found <amount> dead speakers with the garbage collector. Removing them.`

**Expected behavior**
The speakers shouldn't be removed.

**Screenshots**
Ignore the loadbefore warn of spigot (Plugin using non-relocated dependencies)
![image](https://user-images.githubusercontent.com/11576465/83363706-b202ae80-a39b-11ea-83b6-40c362569de6.png)

**Desktop (please complete the following information):**
 - OS:
    - Server: Ubuntu 18.04
 - Browser - (Not used)
 - Version
    - Server: PaperMC Build 284 (MC 1.15.2)
    - OpenAudioMc: 6.3

**Additional context**
There is a mention of the speakers getting de-activated in the update notes, but there is no clear information on how you can disable/prevent this.

**Comment by Mindgamesnl** [comment]
6.3 added a garbage collection task to the speaker service.
What this does is check all the speakers every 30 seconds and go over all the speakers that have loaded chunks (and skip unloaded chunks, since they'll likely be handled later) it then checks every speaker to see if the block at its location is still valid (since a lot of people tend to remove them with worldedit, which leads to resource leaks)

**Comment by Mindgamesnl** [comment]
Are you saying that valid speakers are being removed? since you didn't mention if it broke speakers that should be valid.

**Comment by Andre601** [comment]
> Are you saying that valid speakers are being removed? since you didn't mention if it broke speakers that should be valid.

Yes. The speakers I set are valid (at least I assume so) and there isn't any WorldGuard region with the exception of the global ones that hs things like passthrough disabled.

**Comment by Mindgamesnl** [comment]
Interesting.
Do you use any multi-world plugins? if so, is the speaker in the normal world or is it managed by said plugin?

**Comment by Mindgamesnl** [comment]
Bump

**Comment by Andre601** [comment]
Didn't receice a notification for previous message.
The world isn't the default world, is handled by Multiverse Core and of type the_end.

Another interesting thing is, that the deletion message appears after each server start, so it seems like the speakers aren't really deleted?

**Comment by Mindgamesnl** [comment]
Nope, changed the message, it doesnt hard delete anything to prevent harm but unregisters it for the current session. (its a location thats still in the data file but no longer actually is a speaker block, so it unregisters it for the time being, but rechecks after a restart to not break world backups etc)

**Comment by Andre601** [comment]
Interesting.
It is weird because the blocks are speakers (player heads of OpenAudioMc) and sure not removed or altered so it must be OpenAudioMc seeing them as "invalid" or "dead"

**Comment by Mindgamesnl** [comment]
I assume your real speakers still work, so guess the ones that it removes from the cache are old ones that have been in the file for a while but never got removed, which can happen when breaking/replacing them

**Comment by Mindgamesnl** [comment]
Sorry, but bumping it again since I fail to see how this is a bug (especially after https://github.com/Mindgamesnl/OpenAudioMc/issues/140 )

**Comment by Andre601** [comment]
It is a bug in a way, because clicking a speaker head doesn't open the GUI where you can configure the range of it.

**Comment by Andre601** [comment]
It seems to open/work after opening the audio client (which I assume may have added them back in cache?)
