### ISSUE TITLE
Client closes when there is a start sound

### ISSUE THREAD

**Issue by GwnJernoow** [Mindgamesnl/OpenAudioMc#137]
**Describe the bug**
I have added a start sound when you connect to the client but it always disconnect if you walk in a region with audio as an example. This is not the case when there is no start sound.

**To Reproduce**
1. Go to the client with a start sound
2. Click on connect
3. Go to a region with audio

**Expected behavior**
I hope you can make a fix so the audioclient won't disconnect when there is a start sound.

**Screenshots**
I think i cannot explain the problem with screens...

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: OA 6.3

**Additional context**
I don't have additional context.

Regards,

Jarno Rameijs (AKA GwnJernoow)

**Comment by Mindgamesnl** [comment]
This problem has since been fixed in a client patch, update if you havent already.
