### ISSUE TITLE
Audio Page Logs you out upon joining.

### ISSUE THREAD

**Issue by CoryBorek** [Mindgamesnl/OpenAudioMc#138]
When I type /audio to connect to my host, the link immediately expires upon using
**To Reproduce**
1. Clone the audio server onto your own website.
2.) Configure with OpenAudio+
3.) log into minecraft and type /audio
4.) click the link and notice that it sends you to the documentation page and logs you out immediately

**Expected Behaviour**
OpenAudioMc logs you into the audio server, and you can listen to audio.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version Latest audio server release
 - Minecraft version: 1.14.4
 - OA 6.3

**Additional context**
I have no clue what is going on.

**Comment by Mindgamesnl** [comment]
Do you use your own web client or the one at client.openaudiomc.net?
Because this issue has been fixed and published there two days ago.

**Comment by CoryBorek** [comment]
I was using my own webclient. I first encountered this issue when I updated it to the latest public release. Then I switched it to app.openaudiomc.net. I'll try switching to the client subdomain until it's fixed in the release folder

**Comment by Mindgamesnl** [comment]
Note that app.openaudiomc.net has been deprecated and will get deleted soon, so not surprised that that one doesn't work, was purely for really old clients.

It has been fixed in the public release, please don't open issues unless it happened on the recent production environments of open audio.
