### ISSUE TITLE
Non-relocated dependencies cause loadbefore warning

### ISSUE THREAD

**Issue by Andre601** [Mindgamesnl/OpenAudioMc#139]
**Describe the bug**
When you use plugins that use similar dependencies like OpenAudioMc and aren't relocated either, will Spigot think that they load a class/dependency from OpenAudioMc and sent the loadbefore warning about it.

Dependencies I know this happens with:

- Okhttp3
- okio
- Intrinsics (Kotlin)

**To Reproduce**
1. Have a plugin that uses similar dependencies as OpenAudioMc
    - This also works with passthrough dependencies (i.e. OkHttp3 through JDA)
2. Have OpenAudioMc installed to
3. (Optionally) Make your plugin load or use the dependencies after OpenAudioMc was enabled.
4. You should see loadbefore warnings.

**Expected behavior**
There shouldn't be any loadbefore warnings from spigot regarding the dependencies.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:
    - Server: Ubuntu 18.04
 - Browser: Google Chrome
 - Version: 6.3

**Additional context**

**Comment by Mindgamesnl** [comment]
fixed in https://github.com/Mindgamesnl/OpenAudioMc/commit/92aaf7cdafa99fbbe90e7416a41f44e40c39b556
