### ISSUE TITLE
Add option to directly remove speaker from file when destroying it

### ISSUE THREAD

**Issue by Andre601** [Mindgamesnl/OpenAudioMc#141]
**Is your feature request related to a problem? Please describe.**
When you destroy a speaker, does OpenAudioMc not remove it from the storage.
This is all fine with the reason to not have speakers broken in case of a grief and using a world backup, but using a command each time to remove a speaker is also not good.

**Describe the solution you'd like**
It would be nice to have OpenAudioMc send an additional JSON message where you can click on it, to remove from the storage.
Additionally should the message perhaps be altered to make it more clear that you're not removing the speaker from the storage by destroying it.

Message I had in mind:
> [OA] Speaker was destroyed
> [Remove from Storage]

Clicking `[Remove from Storage]` could run the command to remove a speaker.

**Describe alternatives you've considered**
Only alternative would be to manually run the `openaudio speaker remove <world> <x> <y> <z>` command which is tedious.

**Additional context**

**Comment by Mindgamesnl** [comment]
Made full deletion the default behavior in the latest commit (when manually broken), makes more sense since that's what should have happened, so closing it and labeling it as a bug since that's what it was
