### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Andre601** [Mindgamesnl/OpenAudioMc#145]
**Describe the bug**
You receive the following error when just starting the server:
https://paste.helpch.at/wopegulupu.md

**To Reproduce**
1. Start the server with latest release of OpenAudioMc (See below for version)

**Expected behavior**
Plugin should start normally.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:
    - Server: Ubunut 18.04
 - Browser: Chrome
 - Version:
    - Server: git-paper-371 (MC 1.15.2)
    - Plugin: 6.3.2

**Additional context**

**Comment by Mindgamesnl** [comment]
wtf.jpg
Running the production jar locally without any issues, will throw it on a second server to validate

**Comment by Mindgamesnl** [comment]
Did you do a full restart or a reload? because there were some changes with relocations.
Besides, that, can't replicate it on two servers with the jar directly from spigot.

**Comment by Andre601** [comment]
I made a complete restart (Stopped server, replaced old jar with new one and started again)

Did you check it with the previous version installed (Updating from it)?

**Comment by Andre601** [comment]
The error points to this particular part here:
https://github.com/Mindgamesnl/OpenAudioMc/blob/04e9ffe7d5c9a81bfec507fd00cb4f2b516a9c51/plugin/src/main/java/com/craftmend/openaudiomc/generic/authentication/AuthenticationService.java#L26

**Comment by Mindgamesnl** [comment]
> Did you check it with the previous version installed (Updating from it)?
Yes I did

The line you sent initializes the request to be made later on the boot process if no key set was found, the `RestRequest` class makes some calls and includes fields form okhttp, where shit hits the fan.

Did some fiddling around and decompiled the production jar and one of the class mappings seems to be whack (which is now fixed, uploaded a new jar)
No clue how this ever worked locally, but figure this might be one of those oddball differences between openjdk-jre and the oracle one (or whatever else is out there).

I flushed the cache on Cloudflare for the download site so the jar should be available instantly.

Thanks for noticing!

**Comment by Andre601** [comment]
Can confirm that this is fixed.
Although I would suggest you may look into distributing the jar in different ways, as CloudFlare loves to fuck up requests to GitHub, causing invalid requests on their end ("422 unprocessable entity" if I read it correctly).

This is a common issue with Spigot using CloudFlares DDoS protection and direct downloads from GitHub.

**Comment by Mindgamesnl** [comment]
Cloudflares requests arent going to github, its a webserver of mine
