### ISSUE TITLE
Improve issue templates

### ISSUE THREAD

**Issue by Andre601** [Mindgamesnl/OpenAudioMc#146]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
The issue templates as of now are not quite intuitive, nor useful and leav much open for improvement.
The main issue I face here is, that f.e. The Bug Report template asks for information that is pretty much pointless.
Most issues I myself reported so far had only to do with the server itself and not f.e. with the web client, so having the template split for plugin and client would imo be an improvement as stuff like what Browser you used really isn't needed when reporting a bug with the plugin itself.

Other things are, that certain requested stuff isn't clear enough. For example, what does "Version" mean? Server version? Plugin Version? Browser?

**Describe alternatives you've considered**

**Additional context**

**Comment by Mindgamesnl** [comment]
https://github.com/Mindgamesnl/OpenAudioMc/commit/02a5c53f63359fee4029f175c3c320e97cae5196 Done, old format was pretty much bullshit yeah, just the GitHub template and didn't think too much of it
