### ISSUE TITLE
Embed onto website

### ISSUE THREAD

**Issue by FrozenBeard** [Mindgamesnl/OpenAudioMc#153]
Hi, can you please develop an embed we can copy onto our websites without having to host the client.
Most of my users always have the live map page open anyway, it would be a lot smoother and professional to just have this one page they have open anyway to also have an embed from OpenAudioMC, auth could be done through a code generated in-game.

Thanks.

**Comment by Mindgamesnl** [comment]
You can already do this yourself, just be sure to pass the page query to the iframe.

**Comment by FrozenBeard** [comment]
Im yet to install the plugin and use it haha Quick question about the web UI then, can we at the least disable that giant image on the right? so they just have controls? if its a plain website with a white background and no other elements that would work well.

**Comment by Mindgamesnl** [comment]
You can change it, but not remove it. It'll just resize depending on the viewport size
![image](https://user-images.githubusercontent.com/10709682/90152807-85e6af00-dd88-11ea-926b-0563b495ca85.png)

**Comment by TomLewis** [comment]
> 
> 
> You can change it, but not remove it. It'll just resize depending on the viewport size
> ![image](https://user-images.githubusercontent.com/10709682/90152807-85e6af00-dd88-11ea-926b-0563b495ca85.png)

Aha thanks for the screenshot! I guess it wouldnt work anyway, as they have to `/audio` which would give them a URL (your site) as there is no way for them to enter the code as a parameter from the URL you pass.

Suggestions:

1. Have an option to give them a code in-game to copy into a input box, then have this as a setting we can toggle, then we can embed the page! That will fix the first issue.
2. When embedding all they need is access to the volume slider, the massive image & logo would look very out of place and spoil a website design, so having an option to toggle these off for either just embeds or in general would be nice.

Is the web UI open source? I'm a web developer/designer I could help?

**Comment by Mindgamesnl** [comment]
Won't be implementing either of the suggestions since that would mean that embedding would be an official supported or encouraged feature, but in no way am I looking forward to opening that can of worms.

The UI is open source but has a set of strict rules/guidelines it must follow if you plan to change it (domains and accounts do get banned automatically when they are broken). You can read more about that here https://github.com/Mindgamesnl/OpenAudioMc/blob/master/LICENCE_and_PRIVACY.md

**Comment by TomLewis** [comment]
Shame, the design of that page harms UX.

If you at least added the option to have code entered like plex does (https://www.plex.tv/link/) using embeds then I could host the UI myself and make changes while keeping in tune with your links back to the project.

I would assume the TLDR is don't remove links back to the project like 99.9% of Open Source software, just universal standard.
