### ISSUE TITLE
HTTPS livestream (Icecast2) broken

### ISSUE THREAD

**Issue by jbbjbb** [Mindgamesnl/OpenAudioMc#156]
# Issue Template

**OpenAudioMc Version:** 

6.3.6.3
**Spigot Version:**

Paper version git-Paper-128 (MC:1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**WorldGuard Version:**

7.0.4-beta1:bc551da
**Description of the problem:** 

Seemingly with latest release, can no longer play SSL streaming live Icecast2 stream.  Was working fine circa 10 days ago.  Audio does not surface in browser tab, centovacast shows no listeners.  Using either of the following commands:
/openaudio speaker https://cp3.shoutcheap.com:18000/1
/openaudio speaker https://cp3.shoutcheap.com:18000/1?nocache=59
Client can push a welcome message.  Client shows valid web client connection open.  Have monitored for 48 hours. But I believe I may have had a single 5 second audio burst during that time period).
Audio stream is playing repeating piano loop.  Feel free to connect to audio stream, will try to leave it open and streaming.
**How to replicate the issue:** 

Paste following link in browser, play audio stream as test, and verify certificate validity: https://cp3.shoutcheap.com:18000/1?nocache=59
Create speaker with /openaudio speaker https://cp3.shoutcheap.com:18000/1
Place speaker in Minecraft.
Connect to audio by clicking link.
Click connect in web page that opens.
Return to game and verify audio connection with /audio
Verify or set speaker to 2D audio if needed
Set radius to 18
Listen to silence for 48 hours

**Comment by Mindgamesnl** [comment]
Could you send your config file? Did you disable speaker syncing as instructed in the previous issue that I send you?

**Comment by jbbjbb** [comment]
> Could you send your config file? Did you disable speaker syncing as instructed in the previous issue that I send you?

**Please clarify disable speaker syncing.  Per previous reference:**

> The link that you are using is a live one, which is fine for all non-3D sources, but the problem is that its over http. As described, OpenAudioMc tries to proxy it, and this is where shit hits the fan. The download process fails because its an endless source so it gets timed out, resulting in the client not getting any data and shitting its pants.
> 
> You have a few options from here:
> 
> Accept the non ssl client and downgrade everything to HTTP (go to oa plus (/oa plus), settings, and change https:// to http:// in the client url)
> or (what I recommend, if possible)
> get a SSL certificate for your stream server (if its even yours) to properly support modern web standards.

In steps to replicate, I've outlined we have a legit SSL certificate that shows valid against domain name, and using Icecast2 protocol which broadcasts via https.  By my understanding from above, with 2D speakers, this should allow for live noncached relay. If you are referring to a different link or message, please correct me.

Will update with config file this evening.

**Comment by Mindgamesnl** [comment]
Talked about it in discord a bit ago, its not just ssl, speaker sync also needs to be disabled (hence me asking for the config)

more info: 
![image](https://user-images.githubusercontent.com/10709682/91341038-3917c500-e7d9-11ea-8fab-8af3871e72ca.png)

**Comment by jbbjbb** [comment]
Hey, thank you, and my apologies.  That was team member you communicated that with previously - I've corrected the config file [sync-speakers: false].  That fixed it, and I've doc'd it for future reference.  Would you be interested in contributed doc on icecast stream setup/use for the documentation site?

**Comment by Mindgamesnl** [comment]
Glad that it worked, and of course! feel free to shoot a PR in for an extra page in the docs
