### ISSUE TITLE
No audio coming from 3D speakers

### ISSUE THREAD

**Issue by catronomix** [Mindgamesnl/OpenAudioMc#158]
**Describe the bug**
When switching speakers to 3D mode, the sound just stops, can't get 3D speakers to work with any source.

**Screenshots**
![image](https://user-images.githubusercontent.com/42138122/92602822-efd27580-f2ae-11ea-9cc3-ac2f2c4375d2.png)

**Desktop (please complete the following information):**
 - Plugin Version: 6.3.6.5
 - Server Version: CraftBukkit version git-Spigot-0509002-6b95d59 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT
 - Web client used: client.openaudiomc.net

**Additional context**
No errors appear in admin chat or server console.

**Comment by catronomix** [comment]
Hmm when I leave the server and come back and reopen the web client it does work! Only seems to happen when connected and changing the speaker type to 3D.

**Comment by Mindgamesnl** [comment]
That's correct, you need to re-enter a speakers radius for it to update in the client.
