### ISSUE TITLE
Add http:// support

### ISSUE THREAD

**Issue by GeekCornerGH** [Mindgamesnl/OpenAudioMc#159]
**Is your feature request related to a problem? Please describe.**
I want to use http:// protocol because I am running a localhost server and dont want to port forward

**Describe the solution you'd like**
Adding http protocol support would be fine, i want to try the plugin offline before putting on a production server

**Describe alternatives you've considered**
I saw Mcjukebox, that support local.

**Comment by Mindgamesnl** [comment]
Excuse me?
You can already change the default client URL to be HTTP instead of https in openaudio plus.

Aside from that, OpenAudioMc doesn't require port-forwarding at all since all services that require hosting are ran on our servers, so I really don't know what you're on about.

**Comment by GeekCornerGH** [comment]
So basically, I want to play music from my local server for  developement purposes.

**Comment by Mindgamesnl** [comment]
HTTP gets proxied to HTTPS by a CDN server on our side, either use another source for testing or use a public webserver.

**Comment by GeekCornerGH** [comment]
Can you add an option for disabling your proxy?
