### ISSUE TITLE
Running /volume with no arguments sets volume to -1%

### ISSUE THREAD

**Issue by Technoguyfication** [Mindgamesnl/OpenAudioMc#162]
**Describe the bug**
Running `/volume` in game with no arguments returns a message saying "Your volume has been changed to -1%" but doesn't actually change the volume.

**Screenshots**
![example](https://tkno.pw/3fvQD7t)

**Desktop (please complete the following information):**
 - Plugin Version: 6.3.7.2
 - Server Version: Paper 1.16.4 b282
 - Web client used: client.openaudiomc.net
 - Other setup details: Using Geyser/Floodgate, but they don't interact with OA

**Additional context**
Maybe instead running `/volume` with no args could report the current volume in chat.

**Comment by Mindgamesnl** [comment]
Something to do with third-party software, can't reproduce and has normal behaviour on a clean spigot install.
