### ISSUE TITLE
Bug with the speakers

### ISSUE THREAD

**Issue by PK2-Stimpy** [Mindgamesnl/OpenAudioMc#173]
**Describe the bug**
Basically the bug is when I remove a speaker and restart the server, when I join back the speaker is still playing and it didn't remove from the data.yml

**Desktop (please complete the following information):**
 - Plugin Version:  6.3.7.2
 - Server Version: Paper spigot 1.12.2
 - Web client used: [client.openaudiomc.net (default)]
 - Other setup details: My server is in offline mode and I downloaded the plugin from spigot page

**Comment by Mindgamesnl** [comment]
We don't support old versions of the plugin, this has been fixed in the last release.
