### ISSUE TITLE
Javadocs?

### ISSUE THREAD

**Issue by mrboog12** [Mindgamesnl/OpenAudioMc#177]
After going to https://help.openaudiomc.net/OpenAudioMc/java_api.html

then trying to go to:

**The rest**
This just covers the basics but there’s a lot more you can do, please look in the Javadoc for more details at https://javadoc.openaudiomc.net/

That link does not work, and manually going to it does "This site can’t be reached"

**Comment by Kas-tle** [comment]
https://help.openaudiomc.net/OpenAudioMc/javadoc/overview-summary.html
