### ISSUE TITLE
premissions and bungeecord help me plz

### ISSUE THREAD

**Issue by Goat-Man1** [Mindgamesnl/OpenAudioMc#184]
# Issue Template

**OpenAudioMc Version:** 

**Spigot Version:**
 paper version gitpapper-584

**Description of the problem:** 
I am running a bungeecord server with the openaudiomc plugin and when I do any commands it say [OA] You don't have the permissions to do this, sorry!    and I have op

**How to replicate the issue:** 
 I got it first when I did the /oa accept command

**Comment by Mindgamesnl** [comment]
Please fill out the format or request support in discord
