### ISSUE TITLE
Allow spatial sound to be played once only (speaker/api)

### ISSUE THREAD

**Issue by mkcoldwolf** [Mindgamesnl/OpenAudioMc#190]
**Is your feature request related to a problem? Please describe.**
Spatial sound/media currently does not have ability play once only
instead, the "speaker" feature only offer repeatedly played media
it wouldn't work as the docs said `explosions that spook the living ghost out of someone are even cooler`
bcs they keep "explosioning"

**Describe the solution you'd like**
Allow `playSpatialSound` method in the MediaAPI to pass MediaOptions (set loop)
or whatever passing `only play once` signal to the web server that playing the media

**Comment by ParadoxPixel** [comment]
Check the api: [https://help.openaudiomc.net/java_api.html](https://help.openaudiomc.net/java_api.html)
