### ISSUE TITLE
Speaker Plays after broken with water

### ISSUE THREAD

**Issue by iGreenDogs** [Mindgamesnl/OpenAudioMc#201]
**Describe the bug**
I had a speaker that I wanted to place underwater, and so, I did. Because it was technically a player head, the speaker was destroyed, but there was no chat message (except an internal error) that the speaker was destroyed, and the music kept on playing

**Screenshots**
*video will be available soon*

**Desktop (please complete the following information):**
 - Plugin Version: Latest (as of post)
 - Server Version: Paper spigot 1.17.1
 - Web client used: client.openaudiomc.net

**Comment by mkcoldwolf** [comment]
This is also an issue i notice in my server
When the speaker destroyed by other game mechanic such as water flow or piston or maybe setblock command?
Speakers doesn't update the web backend
Maybe implement a check block conditions when player move (in the event when server send the desired volume to the web backend) can solve this?
While this feature should be togglable as which increase server load

and actually, in theoretically , Owners should install some sort of protection plugins like worldguard or something
to prevent the speaker from destroyed
