### ISSUE TITLE
Speaker and Regions setting not saved.

### ISSUE THREAD

**Issue by KonohanaSakuya2680** [Mindgamesnl/OpenAudioMc#203]
※I'm using Google Translate.

Speaker and region settings are not saved. However, those things seems like in the cache.yml.

Reproduction method → Set the speaker or local music and restart the server.

Minecraft Version→1.12.2
Server system→CatServer-26208f0-universal
Plugin Version→6.5.5

**Comment by Mindgamesnl** [comment]
Failed to reproduce

**Comment by KonohanaSakuya2680** [comment]
Is this relevant?

![SnapCrab_NoName_2021-8-9_16-41-20_No-00](https://user-images.githubusercontent.com/47909539/128673826-4e67c546-cb79-47d9-86cb-4cc5270a251c.png)

**Comment by KonohanaSakuya2680** [comment]
As a result, the cause was that I made data.yml read-only to make it true.

I apologize for the inconvenience this has caused you.
