### ISSUE TITLE
there aren't any speaker within your radious to show

### ISSUE THREAD

**Issue by xjuanst** [Mindgamesnl/OpenAudioMc#215]
I need help with this. I do not understand what is the reason or how to solve it

 - Plugin Version: [eg, 6.5.7]
 - Server Version: [Paper spigot 1.17.1]
 - Web client used: [client.openaudiomc.net ] 
(https://user-images.githubusercontent.com/93793647/140568171-616deb29-a31f-4fc4-a30d-405c8538314b.PNG)
.

**Comment by Mindgamesnl** [comment]
Do you have the webclient open when doing that command?

**Comment by xjuanst** [comment]
> Do you have the webclient open when doing that command?

yeah.I have created an account for the server and link this with the fingerprint but idk what am i doing wrong.

**Comment by ParadoxPixel** [comment]
> yeah.I have created an account for the server and link this with the fingerprint but idk what am i doing wrong.

Created an account and the webclient open are not the same. You can open the client with `/audio`
