### ISSUE TITLE
Fabric Support

### ISSUE THREAD

**Issue by TechPro424** [Mindgamesnl/OpenAudioMc#217]
Please make a Fabric version of this plugin, it is amazing!

**Describe alternatives you've considered**
Considered Simple Voice Chat mod, but it doesn't have features like music

**Comment by Mindgamesnl** [comment]
OpenAudioMc is a plugin at heart, with barebone proxy implementations for BungeeCord and Velocity. Adding a completely separate platform as a plugin implementation isn't worth the time or effort, as it would come with a *lot* more maintenance requirements.
