### ISSUE TITLE
Plugin Can't connect to my server :-/

### ISSUE THREAD

**Issue by Rouchesta** [Mindgamesnl/OpenAudioMc#22]
Hi all, 

I've a problem with the plugin.
It seems to not been connected.
See the result here : http://img4.hostingpics.net/pics/176006disconnected.png

Openaudio 2.0.3
Spigot 1.10.2

Message.yml
Description: This is the place to change the messges, host url and more :)
start-sound: http://audio.teamkog.com/music/HighwayToHell.mp3
website-url: http://audio.teamkog.com/?name=%name%&session=%session%
connect-message: '&9[&bOpenAudioMc&9] &3Click &ehere&3 to connect to our audio server!'
connected-message: '&9[&bOpenAudioMc&9] &3You are now &aConnected&3 our audio server!'
volume-set: '&9[&bVolume&9] &3Your volume has been set to &a%volume%&3%'
volume-error: '&9[&bVolume&9] &4Invalid arguments.'

Is there a port to open on my linux firewall ?

Thanks for your help.

**Comment by Mindgamesnl** [comment]
Hey, sad to see that it's not working for you.
Do you still get this problem after a restart? (not reload!)

**Comment by Rouchesta** [comment]
After a lot of restart, no change :-/

**Comment by Rouchesta** [comment]
Thanks for the reply and help.

Do you get any errors?
**[22:05:18] [Server thread/INFO]: Rouchesta issued server command: /audio
[22:05:18] [Server thread/WARN]: [AutoSaveWorld] Plugin OpenAudio attempted to establish connection http://api.craftmend.com/openaudio/getInfo.php?token=XymGJz8Hznlbcv9 in main server thread
[22:05:18] [Server thread/WARN]: [AutoSaveWorld] Plugin OpenAudio attempted to establish connection socket://api.craftmend.com:80 in main server thread**
What mc version are you using? **Spigot 1.10.2**
What openaudio version are you using? (and is it an official build) **2.0.3 from official website.**
Does you minecraft server say "socket.io connected" at some point. **Yes check first question.**
Can i have a url generated by /audio. **http://audio.teamkog.com/?name=Rouchesta&session=RaroXDZ9sRAs4Mx:ouvul**

Thanks.
Have a good night ;-)

**Comment by Mindgamesnl** [comment]
Tanks but there is one question which you did not awnser :/

Do you get this message AFTERSTARTUP in console?

https://puu.sh/uMPrX/201dad781a.png

**Comment by Rouchesta** [comment]
Thanks for the reply anyway ;-)

Here is the logs at startup 👍 
	Line 77: [06:01:24] [Server thread/INFO]: [OpenAudio] Loading OpenAudio v2.1
	Line 77: [06:01:24] [Server thread/INFO]: [OpenAudio] Loading OpenAudio v2.1
	Line 750: [06:01:46] [Server thread/INFO]: [OpenAudio] Enabling OpenAudio v2.1
	Line 750: [06:01:46] [Server thread/INFO]: [OpenAudio] Enabling OpenAudio v2.1
	Line 751: [06:01:46] [Server thread/INFO]: [OpenAudio] Not all dependencies are installed, all the region functions will NOT work! please install WorldEdit, WorldGuard and WgRegionEvents
	Line 752: [06:01:46] [Server thread/INFO]: [OpenAudio] Loading OpenAudioMc by Mindgamesnl/Me_is_mattyh
	Line 752: [06:01:46] [Server thread/INFO]: [OpenAudio] Loading OpenAudioMc by Mindgamesnl/Me_is_mattyh
	Line 753: [06:01:46] [Server thread/WARN]: [AutoSaveWorld] Plugin OpenAudio attempted to establish connection https://craftmend.com/openaudio.json in main server thread
	Line 753: [06:01:46] [Server thread/WARN]: [AutoSaveWorld] Plugin OpenAudio attempted to establish connection https://craftmend.com/openaudio.json in main server thread
	Line 762: [06:01:46] [Server thread/WARN]: [AutoSaveWorld] Plugin OpenAudio attempted to establish connection socket://craftmend.com:443 in main server thread

**Comment by Mindgamesnl** [comment]
Hmn i find it weird (to say the least) that it starts multiple times, are you sure you have only ONE version in the plugins folder?

**Comment by Rouchesta** [comment]
It's the same line (just the result of my search on "openaudio" in logs.

Right logs here :
Line 78: [11:19:23] [Server thread/INFO]: [OpenAudio] Loading OpenAudio v2.1
Line 766: [11:19:51] [Server thread/INFO]: [OpenAudio] Enabling OpenAudio v2.1
Line 767: [11:19:51] [Server thread/INFO]: [OpenAudio] All dependencies are detected, regions will be enabled!
Line 768: [11:19:51] [Server thread/INFO]: [OpenAudio] Loading OpenAudioMc by Mindgamesnl/Me_is_mattyh

**Comment by Mindgamesnl** [comment]
And no other errors?

**Comment by Rouchesta** [comment]
No :-/

Only on audio.teamkog.com the red message "Disconnected from the server, pleasea wait"

**Comment by Mindgamesnl** [comment]
I mean errors in console + where you host your mc server (you can shoot me an email if you don't want anyone to know which host you use)

**Comment by Rouchesta** [comment]
Online.net (It's a dedicated server running on Linux Debian "Console Mode")
I manage all by myself (MC, Wbsites "Apache", Firewall, ...)

**Comment by Mindgamesnl** [comment]
Can you change settings for the minecraft firewall?

**Comment by Rouchesta** [comment]
Sure.
 It's not a minecraft firewall but a server firewall ;-)

Port 25565 is open for the minecraft to work.
80 and 443 too. Do you need one more for the plugin ?

**Comment by Mindgamesnl** [comment]
I think adding the port 3000 would resolve our issue

(socket.io runs on that)

**Comment by Rouchesta** [comment]
It works :-)
Thank you.
