### ISSUE TITLE
How to use playlist ?

### ISSUE THREAD

**Issue by Rouchesta** [Mindgamesnl/OpenAudioMc#23]
Hi all,

1. How to use playlist with local music in a folder ?

**Regions file :**
Description: Info like region data will be stored here.
region:
  isvalid:
    ville: 'true'
  src:
    ville: http://audio.teamkog.com/music/bobmarley/

I want to play all music in the folder bobmarley.
I create the playlist in playlist.yml

2. How to set the option to stop the music when a player leave a region ?
Cuz by default if i set a music to a region. The music start when i enter the region and don't stop when i leave it.

Thanks for helping ;-)

**Comment by Mindgamesnl** [comment]
1: /openaudio help
playlist info can be found here

And playlists in regions are not possible as of yet, let stand that we can't search a folder for sounds so mp3 files/soundcloud it is (for regions at least)

**Comment by Mindgamesnl** [comment]
Playlists are used to play directly for a player (please read the update log for more info) https://www.spigotmc.org/resources/openaudiomc-open-source-audio-client.30691/update?update=147228

**Comment by Rouchesta** [comment]
Ok for playlist, i understand now. it could be a great feature for next version with random music in a folder option too.

For my second question the problem is that the music don't stop when the player leave the region. In the video "tuto" on youtube i can see that when the player leave, the music stop.

Thank you.

**Comment by Mindgamesnl** [comment]
Listing files in a folder is not gonna happen (sorry) we are stepping away from PHP

And i don't understand what video you are talking about, the region music stops when the player walks out of the region (except from when a region is in another region, that is kinda bugged)
