### ISSUE TITLE
Velocity config file is reset on every restart

### ISSUE THREAD

**Issue by MelvinSnijders** [Mindgamesnl/OpenAudioMc#247]
**Describe the bug**
Every time you restart the velocity server, the config file gets reset and formatted wrong

**Screenshots**
![](https://i.melvinsnijders.nl/gezegdWestphal)

**Desktop (please complete the following information):**
 - Plugin Version: 6.6
 - Server Version: Velocity 3.1.1
 - Web client used: client.openaudiomc.net (default)

**Additional context**
Server is turned off when editing the config.

**Comment by Mindgamesnl** [comment]
Hmn, interesting.
It seems to be writing the data.yml contents into the config, somehow. Fields like public/private, version, cc-locale etc aren’t supposed to end up in the config at all. The formatting makes sense, this is technically valid yaml and some libraries (like the one bundled with velocity) write whacky files like this, by default, for somereason.

You can take a peek in the `VelocityConfiguration` class which implements the configuration properties for that platform and open a pullrequest, it should be fairly straight froward. If you’re unable to, then please let me know so I can take a peek this weekend (probably sunday afternoon~ish).
