### ISSUE TITLE
Error Loading v2.5

### ISSUE THREAD

**Issue by Clarkcj12** [Mindgamesnl/OpenAudioMc#25]
Server Version: 1.11.2 Spigot
Plugin Version: 2.5
Problem: Error Loading Speakers
Error Log: https://gist.github.com/Clarkcj12/7c3942fc5cb7f7fa1a950427998bc02c
Description of Problem on loading the plugin it can't load the speakers.
Other Problem, Plugin in Spigot Zip says 1.5 but loads as v2.5

**Comment by Mindgamesnl** [comment]
Should be fixed in this devbuild, can't test it since im out with family for a week but think it fixes it https://github.com/Mindgamesnl/OpenAudioMc/tree/master/devbuild

**Comment by Mindgamesnl** [comment]
Gonna close it rn, feel free to re-open if it does not work (please note that the devbuild requries java 8 since i dont have java 7 on this laptop and the wifi on this camping is to bad to download it)
