### ISSUE TITLE
[com.craftmend.thirdparty.iosocket.thread.EventThread] Task threw exception

### ISSUE THREAD

**Issue by Frowley95** [Mindgamesnl/OpenAudioMc#251]
**Describe the bug**
A warning message appears when I close my server. It appears to come from craftmend.

**Pastebin**
Pastebin of the issue
https://pastebin.com/1XqzfqXS

**Desktop (please complete the following information):**
 - Plugin Version: 6.6 (latest)
 - Server Version: Purpur 1.18.1 - 1477 (latest)
 - Web client used: [client.openaudiomc.net (default)]
 - Other setup details: Offline mode

**Comment by ParadoxPixel** [comment]
Regarding the exception, it's nothing to worry about. It can occur sometimes when the server is shutting down, but shouldn't do any kind of harm besides a big-ish message in the console.
