### ISSUE TITLE
Plugin OpenAudioMc v6.6 generated an exception while executing task 137

### ISSUE THREAD

**Issue by Frowley95** [Mindgamesnl/OpenAudioMc#252]
**Describe the bug**
When a player left the bug appeared.

**Pastebin**
https://pastebin.com/N8LXrMpj

**Desktop (please complete the following information):**
- Plugin Version: 6.6 (latest)
- Server Version: Purpur 1.18.1 - 1477 (latest)
- Web client used: [client.openaudiomc.net (default)]
- Other setup details: Offline mode

**Comment by Mindgamesnl** [comment]
This bug has been fixed on the master branch and will be released today as a patch
