### ISSUE TITLE
buggy audio

### ISSUE THREAD

**Issue by cusscussyt** [Mindgamesnl/OpenAudioMc#253]
Hi, so i was messing around with the speakers and noticed that when i run around and turn my camera the audio glitches out and sound weird. Its seems like its going weird with like spacial audio and how it changes how loud each headphone piece is.

**Comment by zenoVerboom** [comment]
Experienced the same problem. Please use /oa region for bigger areas for now. He will look into it as soon as possible.

**Comment by Mindgamesnl** [comment]
Ill add it to the todo list, please follow the issue format next time or it'll be closed and marked invalid.

**Comment by Mindgamesnl** [comment]
Location smoothing has been implemented
