### ISSUE TITLE
Show Command

### ISSUE THREAD

**Issue by normotoryjazz** [Mindgamesnl/OpenAudioMc#259]
**Describe the bug**
When using the show command it is impossible to run audio using the "command" function. I tried running "/oa show add (name) (time) command oa play @a (dropbox link)" and it would add the cue and would run the cue but no audio would be generated.

**Desktop (please complete the following information):**
 - Plugin Version: 6.6.2
 - Server Version: Spigot 1.14.4
 - Web client used: client.openaudiomc.net

**Additional context**
I tried making different selections of players, I tried running the command within a region, I tried using different audio. Nothing works.

**Comment by Mindgamesnl** [comment]
If you're still experiencing this issue, please join our discord and show the exact command you used (including the dropbox link), its more likely that it was due to the source, as it will always trigger as a command when added as a cue.
