### ISSUE TITLE
can i create multi voice chat?

### ISSUE THREAD

**Issue by Kanorto** [Mindgamesnl/OpenAudioMc#267]
I have a RolePlay project and there are no other mods / plugins for several voice chats, but I would not want to connect many plugins
I need to **create several voice chats**: 

- Police Walkie Talkie, 
- Radio, 
- Main. 
Can I do it somehow?

**Comment by Kanorto** [comment]
I did not find a closed or open issue on this topic

**Comment by Mindgamesnl** [comment]
You can create group filters through our java API, please use the discord for further support/questions.
