### ISSUE TITLE
Remove the "Open" from the name "OpenAudioMc"

### ISSUE THREAD

**Issue by gonetothisplace** [Mindgamesnl/OpenAudioMc#268]
**Is your feature request related to a problem? Please describe.**
The word “Open” does not reflect the status of this plugin. It's still relying on your service for WS connection for “DRM” and voice chat. Sure, you can sell open source plugin. As long as you provide the entire source for your backend.

**Describe the solution you'd like**
Just remove it. Or change to something else. I'll suggest CloesdAudioMc or SNLAudioMC

**Describe alternatives you've considered**
Maybe if you've come around the internet and found this. And You're looking for alternate. I'll suggest PlasmoVoice.

**Additional context**
bla bla bla, paywall bla bla bla subscription Adobe style bla bla bla.

**Comment by fred913** [comment]
Agree. It's actually not open since the backend server is not open-sourced and there's no alternatives for that.
