### ISSUE TITLE
NullPointerException on startup

### ISSUE THREAD

**Issue by DynamicThijs** [Mindgamesnl/OpenAudioMc#28]
Hey, I'm always getting this error on startup: https://pastebin.com/iUyDhEYj
Next to that, everytime I join, it says:
![updater](https://cloud.githubusercontent.com/assets/17639076/25694766/71d10584-30b0-11e7-84af-9d1e0ad46374.png)

**Comment by Mindgamesnl** [comment]
Both have been fixed in the last devbuild
