### ISSUE TITLE
Multiverse-Core support

### ISSUE THREAD

**Issue by Ectalite** [Mindgamesnl/OpenAudioMc#280]
**Describe the bug**
When starting a show that uses the setblock command, block will be placed in the main world and not in the world where the command `/openaudio show add <showname> 3s command setblock -121 37 290 minecraft:redstone_block` were executed.

**Desktop**
 - Plugin Version: [6.7.2]
 - Server Version: [Paper spigot 1.16.4]
 - Web client used: [audio.europapark-minecraft.eu]
 - Other setup details: [We are using bungeecord]

**Comment by Mindgamesnl** [comment]
I can't quite think of a quick way how (and therefore if) this will be implemented.
OpenAudioMc executes commands from the console, which uses the default level.

I did some previous experiments with faking an entity in a world, and then forcing it that way, but most plugins don't really play with that nicely. I don't really see this as a bug, but more of a limitation with the setblock command as you can't specify worlds. You could look into alternative Redstone triggers (custom show handlers, command alternative or something like rsc)

**Comment by Ectalite** [comment]
Ok thanks for your help
