### ISSUE TITLE
1.19 Bungeecord sending as Actionbar and not Clickable Chat Message

### ISSUE THREAD

**Issue by ItzSkyylark** [Mindgamesnl/OpenAudioMc#281]
**Describe the bug**
Users on 1.19 have noted that when they do "/audio" it is unclickable as its sent as an actionbar message.

**Screenshots**

**Desktop (please complete the following information):**
 - Plugin Version: 6.7.2
 - Server Version: kSpigot-1.12.2
 - Web client used: client.openaudiomc.net
 - Other setup details: running bungeecord/offline/viaversion

**Additional context**
n/a

[1.18.2 and below]
![2022-07-15_17 37 47](https://user-images.githubusercontent.com/99417068/179314050-858487a8-8300-4c5e-88aa-071838db7f1e.png)

[1.19]
![2022-07-15_17 39 56](https://user-images.githubusercontent.com/99417068/179314273-c214f80e-9c28-4ec5-9d37-d64d8873d1e5.png)
[bungee.log](https://github.com/Mindgamesnl/OpenAudioMc/files/9124190/bungee.log) <-- Bungeecord Log
[latest.log](https://github.com/Mindgamesnl/OpenAudioMc/files/9124212/latest.log) <-- Main Server Log

**Comment by Mindgamesnl** [comment]
Only just got the time to look at my github notifications, why was it marked as completed?

**Comment by ItzSkyylark** [comment]
Marked as completed as it was discovered as a ViaVersion issue, not OA, apologies for the inconvenience

**Comment by Mindgamesnl** [comment]
Alright, no worries and good to know!
