### ISSUE TITLE
In game,I input /oa link ,but oa tell me:warning!this command can only be executed on you top-level server!

### ISSUE THREAD

**Issue by charmaznable** [Mindgamesnl/OpenAudioMc#285]
**Describe the bug**
In game,I input /oa link ,but oa tell me:warning!this command can only be executed on you top-level server!

**Screenshots**
![图片](https://user-images.githubusercontent.com/40638503/180595195-11f3144b-31ad-4d1b-9644-24d26caa0b89.png)

**Desktop (please complete the following information):**
 - Plugin Version: [ 6.7.3]
 - Server Version: [ Paper spigot 1.18.1]
 - Web client used: [client.openaudiomc.net (default)]

**Comment by omgbigbone** [comment]
:)

**Comment by Mindgamesnl** [comment]
Is your server running in offline mode? Or do you have a bungeecord instance?
