### ISSUE TITLE
An API for Audiolink plugin creation?

### ISSUE THREAD

**Issue by compieter-gh** [Mindgamesnl/OpenAudioMc#319]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Its something i had in mind from VRChat Audiolink. (might be an stupid idea)
An API too use in plugins using bass mid treble etc.
Idk how it would work but it would make it possible to do particles and block changes (And way more) on the music.

**Describe alternatives you've considered**
I have no idea how there would be any other ways of implementing this.

**Comment by Mindgamesnl** [comment]
The plugin itself doesn't handle audio in a way that it can do spectrum analysis (all media playback and processing is handled within the client tab)

If you really want to accomplish it then I recommend looking into this;
- [StackOverflow from someone asking something similar in Java](https://stackoverflow.com/questions/12879210/how-can-i-draw-sound-data-from-my-wav-file)
- [Archived Stanford ccrma project](https://web.archive.org/web/20080701145826/http://ccrma.stanford.edu/courses/422/projects/WaveFormat/)
