### ISSUE TITLE
No way to print session URL in chat, or use token placeholder.

### ISSUE THREAD

**Issue by coddycrux** [Mindgamesnl/OpenAudioMc#334]
**Is your feature request related to a problem? Please describe.**
I've been trying every way I could to have the /audio link sent as text, as well as clickable. There isn't any placeholder I can use that I'm aware of, and the %oa_token% placeholder doesn't seem to work inside OA.

**Describe the solution you'd like**
Please allow placeholders to be used inside messages sent from OA, or at least mention them in the comments if they do exist.

**Describe alternatives you've considered**
I've considering removing the '.' prefix for bedrock, and having the title sent to everyone, but even then, there's no way to just make one link together with the token (session.openaudiomc.net/[token]). that's all I want.

**Additional context**
 - Plugin Version: 6.8.6
 - Server Version: 1.20.1

**Comment by Mindgamesnl** [comment]
The placeholder requires papi to work.
Please try using {token} in the click-to-connect message, that will still get translated as it was the system before the titles were a thing.

**Comment by coddycrux** [comment]
the {token} placeholder works!
may you please specify the placeholder inside click-to-connect's comment? it'd be really helpful for people trying to customize and match designs to the rest of their server.
