### ISSUE TITLE
Alternative check for Geyser / Bedrock player

### ISSUE THREAD

**Issue by TypicalShavonne** [Mindgamesnl/OpenAudioMc#341]
**Is your feature request related to a problem? Please describe.**
My server dont use a prefix for GeyserMC player, their name do not start with a prefix

**Describe the solution you'd like**
Implement an alternative check for GeyserMC player instead of just checking for the player prefix

**Describe alternatives you've considered**
1. Check for the player UUID, if its start with 00000000, the player might be a GeyserMC / Bedrock player
2. Hook to [Floodgate API](https://wiki.geysermc.org/floodgate/api/) then call the method FloodgateApi#isFloodgatePlayer(UUID) to check if the player isFloodgatePlayer or not

**Additional context**
If the prefix is set to "", Java Player also get the code on the screen

**Comment by Mindgamesnl** [comment]
Hey there!

Is the UUID prefix a consistent identifier for the Geyser player? If so, I'll implement that. (it's a bit hackier compared to using the Floodgate API, but it'll work on vistas as well instead of depending on local libraries)

**Comment by TypicalShavonne** [comment]
https://github.com/GeyserMC/Floodgate/blob/227858930d98dc8e89054b38edebc3b432c0a5eb/core/src/main/java/org/geysermc/floodgate/api/SimpleFloodgateApi.java#L115C21-L115C43
i think yes, but you can reference to Floodgate Code, i think you make replicate this to your code without depending on FloodgateAPI

**Comment by Mindgamesnl** [comment]
oh neato, that's a pretty clever way of going about it.

I'll implement it today and have it in for the next release.

Thanks a ton!
