### ISSUE TITLE
Bug 1.8.8

### ISSUE THREAD

**Issue by trisout78** [Mindgamesnl/OpenAudioMc#359]
**Describe the bug**
I can't generate a audio link

**Screenshots**
![image](https://github.com/Mindgamesnl/OpenAudioMc/assets/81978700/09d339f3-ece2-4bd7-9cce-31c058c11950)

**Desktop (please complete the following information):**
 - Plugin Version: 6.8.8
 - Server Version: Paper 1.8.8
 - Web client used: client.openaudiomc.net
 - Other setup details: Offline mode, Java 11

**Comment by Mindgamesnl** [comment]
No, you just didn’t read the installation instructions.
https://openaudiomc.net/docs/legacy
