### ISSUE TITLE
Error when changing WG Region (OA 2.6 and WGRegionEvent 2.1.0) Spigot 1.10.2

### ISSUE THREAD

**Issue by Rouchesta** [Mindgamesnl/OpenAudioMc#38]
[20:33:26] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to OpenAudioMc v2.6
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-9ff3d7f]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-9ff3d7f]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2.jar:git-Spigot-078e2f8-9ff3d7f]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2.jar:git-Spigot-078e2f8-9ff3d7f]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:610) [spigot-1.10.2.jar:git-Spigot-078e2f8-9ff3d7f]
	at net.minecraft.server.v1_10_R1.PacketPlayInFlying.a(SourceFile:126) [spigot-1.10.2.jar:git-Spigot-078e2f8-9ff3d7f]
	at net.minecraft.server.v1_10_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot-1.10.2.jar:git-Spigot-078e2f8-9ff3d7f]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-078e2f8-9ff3d7f]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-078e2f8-9ff3d7f]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot-1.10.2.jar:git-Spigot-078e2f8-9ff3d7f]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-078e2f8-9ff3d7f]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-078e2f8-9ff3d7f]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-078e2f8-9ff3d7f]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException

**Comment by Mindgamesnl** [comment]
We don't use wgregionevents anymore so thats not the problem lol

**Comment by Mindgamesnl** [comment]
Can you post the full error? this is not helpfull.

**Comment by Rouchesta** [comment]
I only got this error in logs file of my server.
Is there a documentation about new system of Region if you don't use anymore WGRegionEvent ?

`
Description: Info like region data will be stored here.
region:
  isvalid:
    ville_donjon: 'true'
    foret1: 'true'
    foret2: 'true'
    champs: 'true'
    mont: 'true'
    marais: 'true'
    jungle: 'true'
  src:
    ville_donjon: http://XXXX/Pinssamont-15m.mp3
    foret1: http://XXXX/forettiopy-1h.mp3
    foret2: http://XXXX/foretveureulone-20m.mp3
    champs: http://XXXX/champsdemars-18m.mp3
    mont: http://XXXX/montstypitons.mp3
    marais: http://XXXX/marais.mp3
    jungle: http://XXXX/jungle.mp3
world:
  ville_donjon: Donjon
  foret1: Donjon
  foret2: Donjon
  champs: Donjon
  mont: Donjon
  marais: Donjon
  jungle: Donjon
`

**Comment by Mindgamesnl** [comment]
Well this error log is not valid, there has to be something else

**Comment by Rouchesta** [comment]
Its the main log file of Spigot server. There is a flooood of this error making the file very big.
The flood begin when i'm connected to my audio server.

> [15:11:22] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to OpenAudioMc v2.6
> org.bukkit.event.EventException
> 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-9ff3d7f]
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-9ff3d7f]
> 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2.jar:git-Spigot-078e2f8-9ff3d7f]
> 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2.jar:git-Spigot-078e2f8-9ff3d7f]
> 	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:610) [spigot-1.10.2.jar:git-Spigot-078e2f8-9ff3d7f]
> 	at net.minecraft.server.v1_10_R1.PacketPlayInFlying.a(SourceFile:126) [spigot-1.10.2.jar:git-Spigot-078e2f8-9ff3d7f]
> 	at net.minecraft.server.v1_10_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot-1.10.2.jar:git-Spigot-078e2f8-9ff3d7f]
> 	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-078e2f8-9ff3d7f]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
> 	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-078e2f8-9ff3d7f]
> 	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot-1.10.2.jar:git-Spigot-078e2f8-9ff3d7f]
> 	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-078e2f8-9ff3d7f]
> 	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-078e2f8-9ff3d7f]
> 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-078e2f8-9ff3d7f]
> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
> Caused by: java.lang.NullPointerException
> 	at net.openaudiomc.regions.RegionListener.start(RegionListener.java:86) ~[?:?]
> 	at net.openaudiomc.regions.RegionListener.updateRegions(RegionListener.java:148) ~[?:?]
> 	at net.openaudiomc.regions.RegionListener.onPlayerMove(RegionListener.java:115) ~[?:?]
> 	at sun.reflect.GeneratedMethodAccessor181.invoke(Unknown Source) ~[?:?]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
> 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-9ff3d7f]
> 	... 15 more

**Comment by Mindgamesnl** [comment]
Gonna look in to it when i find the time, most likely this weekend

**Comment by Rouchesta** [comment]
Ok thank you. I'll re-upload an old version.

Just donated yresterday to support you Job ;-)

**Comment by Rouchesta** [comment]
Any news ? ;-)

**Comment by Mindgamesnl** [comment]
Finnaly back from a work week, this and next week will be full of testing and hopefully patching, as of yet i've not found anything interesting on this issue (weird behavoir in chrome)

**Comment by Rouchesta** [comment]
I just updated my server to Spigot 1.12
With the last version of OpenAudioMC 2.6

I used the command /openaudio create region http://mydomain/path/music.mp3
It's well added on configuration file but ...

When a player come on my map where sounds are enabled nothing happens until he do /audio and join the web interface in a region with music configured.

For example, i join the Map called "Dungeons", i'm at spawn and i type /audio (+ join web insterface), there is no sound at map spawn ... i walk and enter a region with sound configured ... but the sound never start. The only one way to start this sound is to type again /audio while in the region. Other problem, if i leave this region with the sound started it'll never stop till the end. There is a big problem with Regions events i think.

Thank you for helping ;-)

**Comment by Rouchesta** [comment]
If it can help here is the error log : 

```
Line 135895: [13:07:55] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to OpenAudioMc v2.6
Line 135914: 	at net.openaudiomc.regions.RegionListener.start(RegionListener.java:86) ~[?:?]
Line 135915: 	at net.openaudiomc.regions.RegionListener.updateRegions(RegionListener.java:148) ~[?:?]
Line 135916: 	at net.openaudiomc.regions.RegionListener.onPlayerMove(RegionListener.java:115) ~[?:?]
Line 344876: [13:26:51] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to OpenAudioMc v2.6
Line 344896: [13:26:56] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to OpenAudioMc v2.6
```

**Comment by Mindgamesnl** [comment]
- Fixing it rn! live https://www.youtube.com/channel/UC4GWd7WBrW7F2ooQ4Pa5HWg/live

**Comment by Legoman99573** [comment]
Or Bust ;)

**Comment by Rouchesta** [comment]
I did some new tests on my server.
- When using negative priority on regions it's not working.
- When i use underscore "_" in regions name it's not working.
- Sometimes, the music don't stop and start twice when i enter again.

Thank you.

**Comment by Legoman99573** [comment]
I fixed that in https://github.com/OpenAudioMc/Web-UI-Dev-Builds/

**Comment by Mindgamesnl** [comment]
Hueh, i thought worldguard did ont support negative pro or underscore but lets take a look

**Comment by Legoman99573** [comment]
affects 3rd issue

**Comment by Mindgamesnl** [comment]
Should be fixed in current beta builds :)

(not recommeded to use them yet)
