### ISSUE TITLE
WG Region Events

### ISSUE THREAD

**Issue by TomGrozev** [Mindgamesnl/OpenAudioMc#4]
I get this error when I try to use the regions feature with WG Region Events:

`ERROR Could not pass event RegionEnterEvent to OpenAudio v1.4.4
05.12 12:13:02 [Server] INFO org.bukkit.event.EventException
05.12 12:13:02 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[paperspigot-1.8.jar:git-PaperSpigot-"8b18730"]
05.12 12:13:02 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[paperspigot-1.8.jar:git-PaperSpigot-"8b18730"]
05.12 12:13:02 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[paperspigot-1.8.jar:git-PaperSpigot-"8b18730"]
05.12 12:13:02 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [paperspigot-1.8.jar:git-PaperSpigot-"8b18730"]
05.12 12:13:02 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [paperspigot-1.8.jar:git-PaperSpigot-"8b18730"]
05.12 12:13:02 [Server] INFO at com.mewin.WGRegionEvents.WGRegionEventsListener.updateRegions(WGRegionEventsListener.java:134) [WGRegionEvents-1.2.1.jar:?]
05.12 12:13:02 [Server] INFO at com.mewin.WGRegionEvents.WGRegionEventsListener.onPlayerJoin(WGRegionEventsListener.java:88) [WGRegionEvents-1.2.1.jar:?]
05.12 12:13:02 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
05.12 12:13:02 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
05.12 12:13:02 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
05.12 12:13:02 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
05.12 12:13:02 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) [paperspigot-1.8.jar:git-PaperSpigot-"8b18730"]
05.12 12:13:02 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) [paperspigot-1.8.jar:git-PaperSpigot-"8b18730"]
05.12 12:13:02 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [paperspigot-1.8.jar:git-PaperSpigot-"8b18730"]
05.12 12:13:02 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [paperspigot-1.8.jar:git-PaperSpigot-"8b18730"]
05.12 12:13:02 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [paperspigot-1.8.jar:git-PaperSpigot-"8b18730"]
05.12 12:13:02 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:314) [paperspigot-1.8.jar:git-PaperSpigot-"8b18730"]
05.12 12:13:02 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:173) [paperspigot-1.8.jar:git-PaperSpigot-"8b18730"]
05.12 12:13:02 [Server] INFO at protocolsupport.protocol.transformer.handlers.AbstractLoginListener.b(AbstractLoginListener.java:145) [ProtocolSupport.jar:?]
05.12 12:13:02 [Server] INFO at protocolsupport.protocol.transformer.handlers.AbstractLoginListener.c(AbstractLoginListener.java:91) [ProtocolSupport.jar:?]
05.12 12:13:02 [Server] INFO at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [paperspigot-1.8.jar:git-PaperSpigot-"8b18730"]
05.12 12:13:02 [Server] INFO at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [paperspigot-1.8.jar:git-PaperSpigot-"8b18730"]
05.12 12:13:02 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:875) [paperspigot-1.8.jar:git-PaperSpigot-"8b18730"]
05.12 12:13:02 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [paperspigot-1.8.jar:git-PaperSpigot-"8b18730"]
05.12 12:13:02 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [paperspigot-1.8.jar:git-PaperSpigot-"8b18730"]
05.12 12:13:02 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [paperspigot-1.8.jar:git-PaperSpigot-"8b18730"]
05.12 12:13:02 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]`

**Comment by Mindgamesnl** [comment]
Wich spigot/WgRegion events version are you using?

**Comment by TomGrozev** [comment]
Spigot it 1.8 wgregious is 1.2.1

**Comment by Mindgamesnl** [comment]
Normal spigot? The error log says paperspigot

**Comment by TomGrozev** [comment]
yeah it is paper spigot sorry

**Comment by TomGrozev** [comment]
Any ideas?

**Comment by Mindgamesnl** [comment]
I've never worked with paperspigot nor tested openaudio on it, i'll look for a fix

**Comment by TomGrozev** [comment]
Thank you very much

**Comment by Mindgamesnl** [comment]
does it give any errors when WGRegionEvents is not installed? (and withoud the regions working)

**Comment by TomGrozev** [comment]
No it doesn't have any errors it says it is all good.

**Comment by Mindgamesnl** [comment]
In that case, i think it is a problem with WgrEvents. :/

**Comment by TomGrozev** [comment]
In that case can you please sen me the exact version of it I should be using for 1.8

**Comment by Mindgamesnl** [comment]
I will send it tomorrow, lts pretty late where i life

**Comment by Mindgamesnl** [comment]
Plugins on test server;
WGRegionEvents Continued 2.1.0: https://www.spigotmc.org/resources/wgregionevents-continued.15946/
World guard: https://dev.bukkit.org/projects/worldguard
World edit: https://dev.bukkit.org/projects/worldedit
