### ISSUE TITLE
OpenAudioMc runs in node mode while plugin installed in proxy (FlameCord)

### ISSUE THREAD

**Issue by RTBGG** [Mindgamesnl/OpenAudioMc#415]
**Describe the bug**
I just installed the OpenAudioMc plugin on the proxy server aswell as the 2 Purpur servers following the docs. (https://openaudiomc.net/docs/installation)

When I first connected to the purpur server via the proxy that im using I get the following message (see screenshot below) when I try to use the /oas link command.

I use /oas since I use a proxy and anything starting with /oa doesnt work and I read here on github that using /oas bypasses the proxy and with it I also was able to use the accept command (/oas accept).
However whenever I join the server I somehow still get the "Please use /oa accept" message and as I mentioned /oa accept didn't work for me so I used /oas accept instead.

Error message when using `/oas link`:
```
WARNING! This OpenAudioMc can't accept links, because it's running in node mode.
If you run a proxy (Bunguard, Velocity, Waterfall, etc), then:
- Install the plugin on your proxy, if you have one.
Or, if you don't run one or don't know what this means:
- Enable force-offline-mode in the config.yml if your host doesn't support proxies.
- Or click here to do it automatically, but you need to restart your server after doing this.
```

As I mentioned I installed the plugin on my proxy already. I also already restarted all servers multiple times in attempts to fix this.
As for the second suggestion the plugin gives in the error message:
I host the server using pterodactyl on a server I rented, so the issue that it doesn't support proxies shouldnt apply afaik.

I have searched the configs and web if I can somehow force it to use bungee mode, but it stays in node mode and therefor (I suppose) OpenAudioMc doesn't work in my case. When starting the FlameCord (Waterfall fork) server OpenAudioMc shows no errors.

**Screenshots**
https://share.rtb.gg/file/2024/03/javaw_hSZI8FRUAj.png

**Desktop (please complete the following information):**
 - Plugin Version: 6.10.0
 - Server Version: Purpur 1.20.4 (Build 2153)
 - Web client used: client.openaudiomc.net (default)
 - Other setup details: using a Waterfall fork (FlameCord v1.9.6)

**Additional context**
I am using Luckperms where I am in a Server Admin group with all permissions (using * in LuckPerms) to ensure this isn't a permission issue.

**Comment by RTBGG** [comment]
Okay, well I have tried to make sure that isnt the issue by adding the permission "openaudiomc.commands.accept" to my FlameCord config.yml: https://share.rtb.gg/file/2024/03/firefox_XonRKPTXzN.png
Here is a screenshot of the message I get when running the /oa accept command: https://share.rtb.gg/file/2024/03/javaw_zencP4W2hL.jpg
And here the screenshot of the plugin startup log: https://share.rtb.gg/file/2024/03/firefox_kFQVXPu2w7.png

**Comment by Mindgamesnl** [comment]
I only now had a moment to try to replicate this issue on a clean bungeecord server without anything else, and am not able to replicate this issue. Could you please try using the `openaudiomc.*` permission within the admin group (assuming you have yourself configured as a user for it), and are you not using another permission manager in your proxy besides this? (like luckperms)

**Comment by RTBGG** [comment]
Adding the openaudiomc.* permission to my luckperms editor on the proxy server helped. Sorry the issue was on my side. Thank you for helping tho.
