### ISSUE TITLE
"LoadingPlayerName" Space is missing

### ISSUE THREAD

**Issue by T0biii** [Mindgamesnl/OpenAudioMc#417]
**Describe the bug**
Space is missing between Loading and Playername

**Screenshots**
![image](https://github.com/Mindgamesnl/OpenAudioMc/assets/5702338/ed785a8d-ad74-439e-89ca-febf7d7386de)

https://github.com/Mindgamesnl/OpenAudioMc/blob/4bd6b6588d618eeec255c3cc728c38ae1e427d93/client/src/components/voice/VoicePeerRow.jsx#L117-L118

**Comment by Mindgamesnl** [comment]
Good catch, come to think of it it would be cleaner to be part of the localised strings anyway. Will get this sorted tomorrow.

**Comment by Mindgamesnl** [comment]
Addressed in https://github.com/Mindgamesnl/OpenAudioMc/commit/5a88b10312c9b4d434f7da5dc2d87389a853a86a
