### ISSUE TITLE
Ghost Audio (Chrome) [Speakers don't like live mp3's]

### ISSUE THREAD

**Issue by ssamjh** [Mindgamesnl/OpenAudioMc#45]
It's easier to explain in a video: https://youtu.be/kOHLKSht4Q4

**Comment by Mindgamesnl** [comment]
Live mp3's, cant do anything about it.


Gonna look in to ghoast audio when i find time

**Comment by Legoman99573** [comment]
Fixed issue in https://github.com/OpenAudioMc/Web-UI-Dev-Builds/ @Mindgamesnl close the issue
