### ISSUE TITLE
You are currently missing out on some sounds error

### ISSUE THREAD

**Issue by dgart1574** [Mindgamesnl/OpenAudioMc#452]
nothing works in the plugin...

when I entered "/oa play [link]", minecraft says "You are currently missing out on some sounds! connect with the audio client via /audio" and "Media created and requested to be played for 0 clients", and nothing plays. I couldn't find the way to fix this in the internet, including the site that I reached by using /audio command..

*I put the normal soundcloud link in [link] part.

**Comment by dgart1574** [comment]
minecraft version: paper 1.21
plugin version: 6.10.2

**Comment by Mindgamesnl** [comment]
Could you please send the full command you used to start media?
