### ISSUE TITLE
Allow Direct IP to connect to hue (Will stay opened till finished and debugged)

### ISSUE THREAD

**Issue by Legoman99573** [Mindgamesnl/OpenAudioMc#46]
I felt like adding a milestone so that we know what is done soo far.

- [x] Front end - For putting the IP in when auto detection fails.
- [ ] Back end - Will connect using the IP given.

**Comment by Mindgamesnl** [comment]
Added to planning, should be added by tomorrow

**Comment by Mindgamesnl** [comment]
Working on it!

**Comment by Mindgamesnl** [comment]
Done.

**Comment by Legoman99573** [comment]
fixed a bug anyways :P
