### ISSUE TITLE
Speakers

### ISSUE THREAD

**Issue by Fargus5** [Mindgamesnl/OpenAudioMc#53]
Hi,

I need support with my open audio.

I have this error after reloading it:

`20:22:58 CONSOLE: [INFO] Fargus5 issued server command: /plugman reload OpenAudioMc
20:22:58 OpenAudioMc: Disabling OpenAudioMc v2.6
20:22:59 CONSOLE: ERROR]: Task threw exception
20:22:59 CONSOLE: java.lang.ClassNotFoundException: io.socket.engineio.client.Socket$20$3
20:22:59 CONSOLE: WARN]: Exception in thread "EventThread"
20:22:59 CONSOLE: WARN]: java.lang.NoClassDefFoundError: io/socket/engineio/client/Socket$20$3
20:22:59 CONSOLE: WARN]: at io.socket.engineio.client.Socket$20.run(Socket.java:738)
20:22:59 CONSOLE: WARN]: at io.socket.thread.EventThread.exec(EventThread.java:55)
20:22:59 CONSOLE: WARN]: at io.socket.engineio.client.Socket.close(Socket.java:711)
20:22:59 CONSOLE: WARN]: at io.socket.client.Manager.close(Manager.java:512)
20:22:59 CONSOLE: WARN]: at io.socket.client.Manager.destroy(Manager.java:452)
20:22:59 CONSOLE: WARN]: at io.socket.client.Socket.destroy(Socket.java:421)
20:22:59 CONSOLE: WARN]: at io.socket.client.Socket.access$1400(Socket.java:19)
20:22:59 CONSOLE: WARN]: at io.socket.client.Socket$8.run(Socket.java:438)
20:22:59 CONSOLE: WARN]: at io.socket.thread.EventThread$2.run(EventThread.java:80)
20:22:59 CONSOLE: WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
20:22:59 CONSOLE: WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
20:22:59 CONSOLE: WARN]: at java.lang.Thread.run(Thread.java:745)
20:22:59 CONSOLE: WARN]: Caused by: java.lang.ClassNotFoundException: io.socket.engineio.client.Socket$20$3
20:22:59 CONSOLE: WARN]: at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
20:22:59 CONSOLE: WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
20:22:59 CONSOLE: WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
20:22:59 CONSOLE: WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
20:22:59 CONSOLE: WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
20:22:59 CONSOLE: WARN]: ... 12 more
20:22:59 OpenAudioMc: Enabling OpenAudioMc v2.6
20:22:59 OpenAudio: All dependencies are detected, regions will be enabled!
20:22:59 OpenAudio: All dependencies are detected, regions will be enabled!
20:22:59 OpenAudio: Requesting id for the first time (requesting static token)
20:22:59 OpenAudio: Loading OpenAudioMc by Mindgamesnl/Me_is_mattyh
20:22:59 OpenAudio: Whoah! just like that! loaded the skript events :D
20:22:59 OpenAudio: Loading speakers.
20:22:59 OpenAudio: Started up.`

And  speakers doesn't work.
Speakers have never worked... but regions yes. What is wrong?

I have the mc version 1.12 and the latest version of OA
Let me know if u need anything else to solve my problem... Thanks in advance

**Comment by SnowBlinderYT** [comment]
Hey 

Its never a Good Idea to Reload Plugins 
OpenAudio also doenst like Reloads

**Comment by Fargus5** [comment]
ok

**Comment by ApocalypsjeNL** [comment]
If you change anything about the jar, like replacing it while spigot is running then the plugin is going to throw these errors. As @SnowBlinderYT said it's never a good idea to reload plugins. Just restart the server and the error will be solved

**Comment by Fargus5** [comment]
`[21:44:16] [Server thread/INFO]: [OpenAudioMc] Enabling OpenAudioMc v2.6
[21:44:16] [Server thread/INFO]: [OpenAudio] Not all dependencies are installed, all the region functions will NOT work! please install WorldEdit, WorldGuard and WgRegionEvents
[21:44:16] [Server thread/INFO]: [OpenAudio] Requesting id for the first time (requesting static token)
[21:44:16] [Server thread/INFO]: [OpenAudio] Loading OpenAudioMc by Mindgamesnl/Me_is_mattyh
[21:44:16] [Server thread/INFO]: [OpenAudio] Skript was not found in your server, gues we're not loading the sk-events then.
[21:44:16] [Server thread/INFO]: [OpenAudio] Loading speakers.
[21:44:16] [Server thread/INFO]: [OpenAudio] Started up.`

**I only have this in the console**

**Comment by ApocalypsjeNL** [comment]
Try installing WorldEdit, WorldGuard and WgRegionEvents. At the moment there is a bug where the listener don't work without them. Maybe that fixes your problem

**Comment by Fargus5** [comment]
I already have all of them

**Comment by ApocalypsjeNL** [comment]
Strange, then where does that error come from on startup, (the missing dependencies one)

**Comment by Fargus5** [comment]
Server Information

server.platform: bukkit
server.plugins:

    EasyCourt - Repuska - Combatant - Lift - Vehicles - PlugMan - RPGDrop - SimpleAntiProxy - DreamFish - HPWizard - MaintenanceMode - SimpleAPI - Itemizer - Timber - Realistic-Swimming - InvRestore2 - Modifyworld - VehiclesFlags - WitcheryX - ActionBarAPI - PremiumTurrets - Multiverse-Core - RealisticFish - MCCore - MVdWPlaceholderAPI - FastAsyncWorldEdit - PermissionsEx - RPGHealthIndicator - PEXPlayersRemover - RPGFood - TimeFold - FastAsyncVoxelSniper - PlaceholderAPI - UltimateTs - PorteCoulissante - NametagEdit - GeneralLib - CompaniesManager - RPGMiner - TitleAPI - EpicWorldGenerator - Graves - ParticleLIB - PartySystem - MOTD - CoreProtect - WorldEdit - OpenInv - Essentials - PlayerMention - TreasureChest - MysteryBoxes - SQLibrary - EffectLib - Vault - ChairStairs - MassiveCore - CreativeGates - StreetlightsAdvanced - EssentialsGeoIP - GrowingOres - AddLight - MyCommand - EpicNetherGenerator - ServerTutorialPlus - MessageAnnouncer - Reporter - Calendar - EssentialsChat - SkillAPI - SignColors - EssentialsProtect - EssentialsAntiBuild - EssentialsSpawn - InfernalMobs - AdvancedAchievements - OpenAudioMc - BKCommonLib - Train_Carts - TrainCartsOA - RPGHorses - HolographicDisplays - Cinematic-Death - RPGMobMoney - RPGPlayerLeveling - MythicMobs - Quests - Statz - Skript - SkAction - LargeSk - WildSkript - NPCDestinations_Animator - SimplePets - Citizens - NPC_Destinations - NPC_Police - CarlTheCreeper - WorldGuard - ResourceGens - Blacksmith - ShopChest - CommandNPC - WorldGuardPushBack - NavyCraft - Kingdoms - Sentinel - NPCDestinations_Farmer - WGRegionEvents - PirateSK - Hotels - ChatActions - Skills - Sentries - ProtocolLib - ChatItem - WorldEditSelectionVisualizer - skRayFall - TransportPipes - ChangeSkin - LiteBans - LibsDisguises - RealVillagerTowns - VanishNoPacket - RPGInventory - FactionMobs - DisguiseAbilities - VoxelSniper
    server.version: git-Spigot-8cbfc85-202da97 (MC: 1.12) / 1.12-R0.1-SNAPSHOT

**Comment by ApocalypsjeNL** [comment]
Which version of the plugin do you use?

**Comment by Fargus5** [comment]
2.6

**Comment by ApocalypsjeNL** [comment]
strange, I got it to work on Craftbukkit 1.12 and only the 2.6 spigot version

**Comment by Fargus5** [comment]
It's been a long time since I'm reporting this issue

**Comment by Mindgamesnl** [comment]
If is fixed in the devbuilds, no shit it wont work in the old version lol

**Comment by Mindgamesnl** [comment]
At least, the current "build"

**Comment by Fargus5** [comment]
2.6 is the latest version... what do u mean? It's on spigot...

**Comment by ApocalypsjeNL** [comment]
He means this one:  https://github.com/Mindgamesnl/OpenAudioMc/blob/master/Plugin%20source%20code/target/OpenAudioMc-2.7-pre3.jar

**Comment by Fargus5** [comment]
If you not public on spigot we cannot devine... thanks in advance. I will let you know if it works.

**Comment by Fargus5** [comment]
I have this:
I go to home, i will test, and i will let you know

[17:10:55] [Server thread/INFO]: [OpenAudioMc] Enabling OpenAudioMc v2.7-pre3
[17:10:55] [Server thread/INFO]: [OpenAudioMc] Loading OpenAudioMc by Mindgamesnl/Me_is_mattyh
[17:10:55] [Server thread/INFO]: [OpenAudioMc] Not all dependencies are installed, the region functions will NOT work! please install WorldEdit and WorldGuard
[17:10:55] [Server thread/INFO]: [OpenAudioMc] Skript was not found in your server, guess we're not loading the sk-events then.
[17:10:55] [Server thread/INFO]: [OpenAudioMc] Requesting id for the first time (requesting static token)
[17:10:55] [Server thread/INFO]: [OpenAudioMc] Reflection has found MC v1_12_R1 which is supported
[17:10:55] [Server thread/INFO]: [OpenAudioMc] OpenAudio started in 78ms!

**Comment by Mindgamesnl** [comment]
it is not a public bug for a reason.

The speaker bug has been fixed but if it was a stable build we would have released it by now,

Gihtub is for work in progress code.

**Comment by ApocalypsjeNL** [comment]
Yeah I maybe know why the dependencies says you've not installed them, gonna test something

**Comment by Fargus5** [comment]
When I do /audio and I connect:

20:22:16 CONSOLE: [INFO] Fargus5 issued server command: /audio
20:22:16 CONSOLE: [INFO] Reconnecting to the openaudiomc socket server.
20:22:16 CONSOLE: WARN]: Exception in thread "OkHttp Dispatcher"
20:22:16 CONSOLE: WARN]: java.lang.NullPointerException: proxySelector == null
20:22:16 CONSOLE: WARN]: at okhttp3.Address.<init>(Address.java:79)
20:22:16 CONSOLE: WARN]: at okhttp3.internal.http.RetryAndFollowUpInterceptor.createAddress(RetryAndFollowUpInterceptor.java:199)
20:22:16 CONSOLE: WARN]: at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:107)
20:22:16 CONSOLE: WARN]: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
20:22:16 CONSOLE: WARN]: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
20:22:16 CONSOLE: WARN]: at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
20:22:16 CONSOLE: WARN]: at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
20:22:16 CONSOLE: WARN]: at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
20:22:16 CONSOLE: WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
20:22:16 CONSOLE: WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
20:22:16 CONSOLE: WARN]: at java.lang.Thread.run(Thread.java:745)
20:22:16 OpenAudioMc: Socket.io connected


So regions are not working...maybe a cause it's not reading skript and we and wg... u have to fix this becouse both workend in 2.6.

**Comment by SnowBlinderYT** [comment]
What Version are you Currently Using @Fargus5 ?

**Comment by Fargus5** [comment]
Please read up before ;)
Anyway: OpenAudioMc v2.7-pre3

**Comment by SnowBlinderYT** [comment]
There are some Problems with the Source Code / Dev Builds 
We are currently Fixing some Bugs (Speakers / Regions / etc.)
Please use 2.6 if you want a "stable" Version :3

**Comment by Fargus5** [comment]
I used this, but they told me to download the new one becouse speakers doesn't work.

**Comment by Legoman99573** [comment]
Not recommended to reload plugins. Best option is to restart a server ;). Plus its bad practice on production servers.

**Comment by Fargus5** [comment]
I didn't reloaded anymore. Where I can find the new relased dev builds to stay update?

**Comment by Mindgamesnl** [comment]
Wait for release.
