### ISSUE TITLE
[BUG] OpenAudio & WorldGuard Regions

### ISSUE THREAD

**Issue by Rouchesta** [Mindgamesnl/OpenAudioMc#61]
When a flag "enderpearl-deny" is applied on a region with WorldGuard, worldguard display error message when using enderpearl but teleport the player. If i remove Openaudio plugin the flag work properly and the player is not teleported.

I think the problem is in the code part where enter/exit of the player is managed.
`public enum MovementWay
{
  MOVE,  TELEPORT,  SPAWN,  DISCONNECT;
  
  private MovementWay() {}
}`

In fact the teleportation is understanded by WorldGuard but something hoolek with Openaudio and cancel the "Deny" for the player. I think Openaudio has a higer priority on the event occured by the teleportation.

Can you have a look ?

Thank you.

**Comment by ApocalypsjeNL** [comment]
Which error do you get?

**Comment by Rouchesta** [comment]
There is no error i'ts just a fact. Conflict between 2 plugins.

**Comment by Legoman99573** [comment]
Version of the server and version of worldguard. It will help us out so we can try to replicate and see if we get the same issue on our end.

**Comment by Rouchesta** [comment]
Spigot 1.12 and Openaudio 2.6
So it's worldguard side ? :-/
If i remove Openaudio the flag works pproperly. 0.o

**Comment by Legoman99573** [comment]
Version of worldguard?

run ``/version Worldguard`` in game and post it here.

**Comment by Rouchesta** [comment]
6.2.1

**Comment by Legoman99573** [comment]
Would recommend updating then to the latest development build of WorldGuard http://builds.enginehub.org/job/worldguard/last-successful?branch=master

Version should be 6.2.2

**Comment by Rouchesta** [comment]
NOthing change with latest version.

**Comment by Legoman99573** [comment]
3.0 should hopefully address it, but i think its still worldguard side.

**Comment by Rouchesta** [comment]
I'll wait for 3.0 ;-)

**Comment by Mindgamesnl** [comment]
Oh golly it has been a while, phew.

Any how, in 4.0 (which hopefully releases tomorrow) no longer relies on the events and thus fixes this issue :)

**Comment by Rouchesta** [comment]
Thank you i'll test it as soon as the release is available.

**Comment by ApocalypsjeNL** [comment]
Update is live, gonna close the issue then. If you've any bugs feel free to reopen it. https://www.spigotmc.org/resources/openaudiomc-open-source-audio-client.30691/update?update=212895
