### ISSUE TITLE
Feature Request - Disable Playback position remembering

### ISSUE THREAD

**Issue by GewoonBoyke** [Mindgamesnl/OpenAudioMc#80]
Feature Request

Hello, 

Maby for an next update it will be nice if there is an option to Restart the sound if a player walk out/in an region..

If my players walk out of an region the music stops, but if they walk back in the music will play where it has stopped (So it remembers the playback position)

Maby you can add an string or setting so you can disable this saving of the playback position and the music restarts every time the players walks in and out an region. (Like i said on discord :P)

Bye,
Boyke

**Comment by Mindgamesnl** [comment]
pretty neat, +1 todo

**Comment by SnowBlinderP** [comment]
+1

**Comment by Snicser** [comment]
+1

**Comment by Mindgamesnl** [comment]
Implemented.

https://github.com/Mindgamesnl/OpenAudioMc/commit/0fa44fa1fbd9f91b8b25543ea5254e15b186eb58
