### ISSUE TITLE
4.0 Fires PlayerQuitEvent when lost connection to socket server (50% of the time)

### ISSUE THREAD

**Issue by Legoman99573** [Mindgamesnl/OpenAudioMc#83]
# Issue Template

**OpenAudioMc Version:**
4.0

**Spigot Version:**
PaperSpigot version git-Paper-1341 (MC: 1.12.2)

**Description of the problem:** 
While i was playing an audio for a loop, i see a player leave event fired at the same time the audio server disconnects, but i am still in the server. Console wont show up as a quit event.

**How to replicate the issue:** 
1. Connect to the audio server
2. Wait for audio server to disconnect
3. Have a plugin that checks for Player Quit Event, I used my discord bot, that reads the PlayerQuitEvent
Discord Bot:
![image](https://user-images.githubusercontent.com/7460704/37089955-21e0bd76-21c8-11e8-845b-51f557308bf1.png)
Console:
![image](https://user-images.githubusercontent.com/7460704/37090040-656a91de-21c8-11e8-99b5-04c5d459dcc7.png)

**Comment by ApocalypsjeNL** [comment]
We don't call any bukkit events, we only listen to them. Seems like a different plugin is causing this issue
