### ISSUE TITLE
Beginning of audio get cut out / Ability to toggle fade-in and fade-out

### ISSUE THREAD

**Issue by ThisTNTSquid** [Mindgamesnl/OpenAudioMc#89]
# Feature Request / Bug

**Spigot Version:** 1.12.2
**OA Version:** 4.0

> By looking at the title , this should be 2 separated issues, but I believe they are related and one of them is causing the other to happen (it may not be the truth) , but anyways I'm opening one single for 2 of them

First I would like to report the problem (or phenomenon) about the heading 1-2 seconds of audio is being cut out everytime an audio is being played. If it is caused by network delay, it will be better to have the **whole audio wait until the delay is done** before actually start playing. I'm not blaming anyone for this as this is not something really very major, and a manual hack by adding a bleeding buffer in front of every audio could **relieve** this problem, but consider adding in this bleeding buffer to EVERY SINGLE audio the server is in use right now is simply unfeasable and redundant as there are more than 30 of them right now. (actually this problem rendered my metro announcement system half-unusable) I hope this one can be fixed in short future

Next is concerning the fade-in and fade-out (specifically fade-in). I notice sometimes the fade-in is responsible for eating up some sounds at the beginning 1-2 seconds of the audio (i dont really know whether it is the real cause, but from my observation, it seems to be) But whether it is the real reason for eating up some audio or not, it will still be very weird to "fade-in" station announcements and sound effects in my metro system. So , I hope there will be a config option to toggle the use of fade-in and fade-out (or at least an option in command to disable fading in and out)

**Comment by Mindgamesnl** [comment]
Fixed for new relese in 2019 rewrite.
