### ISSUE TITLE
OpenaudioMC doesn't work with Chrome

### ISSUE THREAD

**Issue by Engineer204** [Mindgamesnl/OpenAudioMc#93]
Hello! I am receiving an issue where when players are connecting using Chrome, nobody can hear anything. I do not have any error codes, however I have found that it works on Edge, and Firefox. I have told my players to use those, but most of them refuse to do so. If there is any way for you to re-add chrome support that would be amazing! Thanks for all you do! Hope to see new versions coming soon!

**Comment by Mindgamesnl** [comment]
Fixed for new relese in 2019 rewrite.
