### ISSUE TITLE
unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by Sprax2013** [Mindgamesnl/OpenAudioMc#94]
# Issue Template

**OpenAudioMc Version:** 4.0

**Spigot Version:**  This server is running CraftBukkit version git-Spigot-2cf50f0-2b93d83 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**WorldGuard Version:** WorldGuard version 6.2.1;84bc322

**Description of the problem:** The plugin throws an Exception when trying to enable and after server start, it does not respond to commands or anything.

**How to replicate the issue:** Idk...
My Java-Version:
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1~deb9u1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

Just start a Spigot 1.12.2 server I guess.
I did not make any changes to the config.

**Comment by realjax** [comment]
+1 

PKIX path building failed

**Comment by ApocalypsjeNL** [comment]
Can you try this one? (note I can't upload somewhere so I share it at the discord) https://discordapp.com/channels/245497740589662209/245498457681428480/482283444492173313

**Comment by Sprax2013** [comment]
This version is working and I can connect to the Web-Audio-Client and play a URL without any problems

**Comment by Mindgamesnl** [comment]
Fixed for new relese in 2019 rewrite.
