### ISSUE TITLE
niet opslaan van data

### ISSUE THREAD

**Issue by djbenbe** [Mindgamesnl/OpenAudioMc#98]
**OpenAudioMc Version:** 
5.0
**Spigot Version:**
1.13.2-r01-snapshot
**WorldGuard Version:**
WorldGuard 7.0.0 Beta 3

**Description of the problem:** 
het opslaan van region en speakers werken niet

**Comment by Mindgamesnl** [comment]
al gefixeed, bovendien graag engels houden.

Goede morgen, het is 3 uur snachts.
Gezien je hier op github zit, heb je al kunnen zien dat deze issue al resolved is

https://github.com/Mindgamesnl/OpenAudioMc/commit/147a211fd889b4f7bdc30523cd92e3f1d19be9d6
